### PR TITLE
Upgrade develop branch to work with ubuntu-latest.

### PR DESCRIPTION
**Pull request by Elliria**
The same PR as before, but with the addition of @userdocs' merged PR and a couple of lines in the CHANGELOG.rst file describing the two PRs for the AutoKey upgrade.

### CODE REVIEW

**Comment by Elliria** [comment]
OMG, the suspense...

**Comment by Elliria** [comment]
Weehaw, finally. You guys are all amazing. This was a great team effort. Hugs all the way around.

**Comment by josephj11** [comment]
I'm still seeing two failed tasks, so I'm not doing anything yet

>clean: failed with pass_env values cannot contain whitespace, use comma to have multiple values in a single line, invalid values found 'DISPLAY DBUS_SESSION_BUS_ADDRESS USER'

**Comment by userdocs** [comment]
That looks fixed in the PR, so where are you seeing it? It's not there in the checks?

https://github.com/autokey/autokey/pull/786/files#diff-fa602a8a75dc9dcc92261bac5f533c2a85e34fcceaff63b3a3a81d9acde2fc52R45

**Comment by josephj11** [comment]
> That looks fixed in the PR, so where are you seeing it? It's not there in the checks?
> 
> https://github.com/autokey/autokey/pull/786/files#diff-fa602a8a75dc9dcc92261bac5f533c2a85e34fcceaff63b3a3a81d9acde2fc52R45

I looked at Elleria's post from 10 hours ago and clicked on an issue with a red X next to it.

I missed the real deal at the bottom of the issue.

I presume I should mrege this now, but I'll wait for confirmation.

At some point, I can give Elleria permission to do this herself if she wants it.

**Comment by Elliria** [comment]
I'm seeing all green check-marks at my end (weehaw): [https://github.com/autokey/autokey/pull/786/checks](https://github.com/autokey/autokey/pull/786/checks)

I'm seeing what @userdocs [is seeing](https://github.com/autokey/autokey/pull/786/files#diff-fa602a8a75dc9dcc92261bac5f533c2a85e34fcceaff63b3a3a81d9acde2fc52R45) with the offending line having been fixed.

It's line 45 in the **setup.cfg** file and I had made that repair a couple/few PRs ago and included it in this PR. If you look at [line 45 of setup.cfg](https://github.com/Elliria/fork/blob/develop/setup.cfg#L45) in my fork's **develop** branch, you'll see that that's fixed.

I wonder why you're getting a red x at your end. The GitHub gods seem to be determined to somehow thwart this PR. Should I cancel it and try submitting it again?

**Comment by Elliria** [comment]
Okay, I'm seeing the two red x marks now. That's odd. It says that all checks have passed down here and even gives me green check-marks when I click "Show all checks" in that little indicator, but the red x marks are up at the top. I'll try to figure those out.

**Comment by Elliria** [comment]
It's bizarre:

Red


Green

**Comment by Elliria** [comment]
Maybe the order that things are done in really does matter. Perhaps I should scrap this fork, fork the project again, and make that change be the first or one of the first changes? It's possible that it does the tests in the order it receives them and uses the files in the condition they were in at the time of that commit, which would explain why it's not yet seeing the commas.

The only other thing I can think is that even though the line currently looks like this:
```
passenv = DISPLAY,DBUS_SESSION_BUS_ADDRESS,USER
```
It is counting the space before **DISPLAY** as a leading space, so maybe it should be written like this:
```
passenv =DISPLAY,DBUS_SESSION_BUS_ADDRESS,USER
```
*That looks all kinds of wrong, though, and is sending up red flags on my personal aesthetics meter.*

Maybe quoting it would work?
```
passenv = "DISPLAY,DBUS_SESSION_BUS_ADDRESS,USER"
```
Or quoting each part of it?
```
passenv = "DISPLAY","DBUS_SESSION_BUS_ADDRESS","USER"
```

**Comment by Elliria** [comment]
I think I've got it.

Instead of:
```
passenv = FOO BAR
```
It wants:
```
passenv =
    FOO
    BAR
```
I'm closing this pull request and doing another.

Good catch, @josephj11!

**Pull request closed without merging**
