### PR TITLE
Update the GTK and Qt man pages.

### PR DESCRIPTION
**Pull request by Elliria**
* Move the date to the top of the document.
* Update the date.
* Move TeX instructions up with the rest of the instructions.
* Add the **SEE ALSO** section.
* In the **NAME** section:
  * Update the text.
* In the **SYNOPSIS** section:
  * Reformat the section.
  * Add the options to the example command.
* In the **DESCRIPTION** section:
  * Reformat the section.
  * Remove unnecessary information.
  * Update the text.
* In the **OPTIONS** section:
  * Reformat the section.
  * Sort the section alphabetically.
  * Update the section's introductory text.
  * Reformat the **cutelog** option.
  * Add the short **cutelog** command-line switch.
  * Rename the long **cutelog** command-line switch.
  * Update the **cutelog** option's description.
  * Update the **mouse** option's description.
  * Add the short **verbose** command-line switch.
  * Deprecate the short **verbose** -l command-line switch.
  * Update the**verbose** option's description.
  * Update the **version** option's description.
* In the **AUTHOR** section:
  * Remove man-page-authorship attribution.
  * Update the text.
* In the **SEE ALSO** section:
  * Move the **cutelog** link from the **OPTIONS** section to the **SEE ALSO** section.
  * Move the wiki link from the **DESCRIPTION** section to the **SEE ALSO** section.
  * Add man-page links.
  * Add other links.

### CODE REVIEW

**Comment by Elliria** [comment]
As usual, you can download the man pages in this pull request from my fork to view them. You can get the GTK man page [here](https://github.com/Elliria/autokey/blob/develop/doc/man/autokey-gtk.1) and the Qt man page [here](https://github.com/Elliria/autokey/blob/develop/doc/man/autokey-qt.1), using the download button in the upper right corner of each. Then you can open the directory they're in in a terminal window and type `man ./autokey-gtk.1` and `man ./autokey-qt.1` to view them as man pages.

**Review by josephj11 — CHANGES_REQUESTED** [review]
All good except

24 ...desktop/script-automation utility using GTK

I'm willing to leave it as is, but it's not technically correct.

**Review by josephj11 — CHANGES_REQUESTED** [review]
All good except

24 ...desktop/script-automation utility using Qt

I'm willing to leave it as is, but it's not technically correct

**Comment by Elliria** [comment]
> All good except
> 
> 24 ...desktop/script-automation utility using Qt
> 
> I'm willing to leave it as is, but it's not technically correct

[You suggested it here](https://github.com/autokey/autokey/pull/867#issuecomment-1572929989), so I went with it. Are you disagreeing with yourself now and do you have an alternative suggestion that we haven't already considered or would you like to go with the one we had considered and replaced with that one?

**Comment by josephj11** [comment]
> > All good except
> > 24 ...desktop/script-automation utility using Qt
> > I'm willing to leave it as is, but it's not technically correct
> 
> [You suggested it here](https://github.com/autokey/autokey/pull/867#issuecomment-1572929989), so I went with it. Are you disagreeing with yourself now and do you have an alternative suggestion that we haven't already considered or would you like to go with the one we had considered and replaced with that one?

What I am seeing in the PRs is:

`\fBautokey-gtk\fR  \- desktop/script-automation utility for GNOME`

and

`\fBautokey-qt\fR \- desktop/script-automation utility for KDE`

Am I looking at old code by accident again?

**Comment by Elliria** [comment]
No. That's in the current versions of the man pages in this pull request.

This is what it says in the man page dedicated to the AutoKey variant for use under GNOME:
```
\fBautokey-gtk\fR  \- desktop/script-automation utility for GNOME
```
This is what it says in the man page dedicated to the AutoKey variant for use under KDE:
```
\fBautokey-qt\fR \- desktop/script-automation utility for KDE
```
Those are brief summaries that give an at-a-glance description of what you're getting. The very next section goes into detail.

What are you feeling is technically incorrect with those?

**Comment by josephj11** [comment]
@Elliria What's technically incorrect are the premises of "under KDE" and "under GNOME". You can easily use GTK and Qt applications under any DTE that allows those libraries to function correctly. I run autokey-gtk under KDE any time I want to test it. I am not running it under GNOME. I don't even have GNOME installed on my system. DTE and GUI libraries are two separate things.

The only way the larger environment is involved is if I were to install autokey-qt on a system with no other Qt aplications already installed. Then a large bunch of dependencies  for Qt would be installed automatically.

The same is true in reverse for autokey-gtk, but it is much less likely that my system would not already have other GTK apps installed and so the necessary dependencies for GTK would probably already be installed.

**Comment by Elliria** [comment]
Are these technically incorrect or would they work?
```python
\fBautokey-gtk\fR  \- desktop/script-automation utility that uses the GTK toolkit
```
and:
```python
\fBautokey-qt\fR \- desktop/script-automation utility that uses the Qt toolkit
```

**Comment by josephj11** [comment]
Your latest version is technically correct. Mine just uses a couple less words. Either is fine with me.

**Comment by Elliria** [comment]
We must be looking at different copies of the files in question. They have exactly the same number of words:

[Yours](https://github.com/autokey/autokey/pull/867#issuecomment-1572929989):
```
\fBautokey-gtk\fR  \- desktop/script-automation utility with a GTK-based graphical interface
```
Mine:
```
\fBautokey-gtk\fR  \- desktop/script-automation utility that uses the GTK toolkit
```
But let's go with yours so we can get this across the finish line. I've made the change and updated the PR.

**Comment by josephj11** [comment]
I was going from memory and was wrong about the word count.
I'm merging this, but I don't see the actual man pages. Maybe that's in a subsequent PR I haven't read yet.

**Comment by Elliria** [comment]
> I'm merging this, but I don't see the actual man pages. Maybe that's in a subsequent PR I haven't read yet.

When you merged this pull request, you merged all of the commits that were part of it. That includes the original commits that started the pull request, as seen at the top of this page:

top

And the changes you requested that were added as additional commits to it yesterday, as seen at the bottom of this page:

bottom

The only way to do a "clean" PR with nothing but pure commits that pass muster and none that need changing would be to close a pull request without merging it and then start a new one. In this case, the changes were minor, so I decided not to start over.

**Comment by josephj11** [comment]
OK. That makes sense. No need to do it differently. This was a piece of work!

**Comment by Elliria** [comment]
This pull request satisfied issue #682, discussion #840, and finished satisfying issue #845.

**Pull request merged**
