### PR TITLE
Add set_clipboard_image method to Gtk and Qt clipboard implementations.

### PR DESCRIPTION
**Pull request by sebastiansam55**
Fix for #526, adds `set_clipboard_image` methods to both the Qt and Gtk interfaces for the clipboard. Uses native library as opposed to `xclip` as was originally suggested.

`set_clipboard_image` takes one argument, a path to a image file on the local filesystem that will be loaded into the clipboard for pasting.

### CODE REVIEW

**Comment by sebastiansam55** [comment]
Open to any suggestions on implementation! Or function name or anything else.

**Comment by josephj11** [comment]
What about putting an image from a webpage into the clipboard? Would it first have to be downloaded by a script? Wouldn't this be a frequent use case? I didn't look at the code.

**Comment by sebastiansam55** [comment]
I'm not sure what the most common use case for something like this is, just throwing it out there as it was requested and implementation seemed pretty trivial. 

Idk I feel like most people would be using something like this with local files? Like what is the scenario where you know the url of the file, have gone to the trouble of using autokey to automate the pasting of it, but don't use it often enough to have it saved locally?

Implementation of URL based clipboard function in a autokey script would look something like this;

```python
import requests
import tempfile
url="https://avatars.githubusercontent.com/u/1707320?s=80&v=4"
r = requests.get(url)

with tempfile.NamedTemporaryFile() as f:
    f.write(r.content)
    clipboard.set_clipboard_image(f.name)
```

**Comment by sebastiansam55** [comment]
Re: implementation

What do you think about adding it into `set_clipboard` main and adding an additional optional argument like `content_type` which could be set to text by default, images and I believe that there is a way to "copy" files in no the clipboard?

Like when you copy paste in a gui file browser I believe that is done via the same sort of method. I'll look into it more Monday, just a thought I had

**Comment by sebastiansam55** [comment]
I should also wrap the gtk version in the gdk enter threads like the other ones, I had no issues in briefly testing it but there is probably a reason the other methods wrap like that

**Comment by josephj11** [comment]
I have to think about it more. My first impression was that whenever I am doing anything with images, they're usually on a someone else's webpage. I would like to write a script to save a Dilbert or other cartoon to a local file with a descriptive file name, probably from an input dialog box. I'd have to try to actually build it to see what is required to get it to work. I'm sure I could do this given some time to work on it.

**Review by BlueDrink9 — APPROVED** [review]
I'm happy with it as-is. I'd prefer changes like this to changes that alter existing interfaces.

**Comment by BlueDrink9** [comment]
Actually, since I mentioned it in the Gitter, could you please add this change to the CHANGELOG as part of this PR

**Comment by BlueDrink9** [comment]
> I should also wrap the gtk version in the gdk enter threads like the other ones, I had no issues in briefly testing it but there is probably a reason the other methods wrap like that

I too would like to know what they do. I found some inconsistencies that seemed not to have mattered while doing refactors, so I suspect it may be a case of monkey see = do in some places. Still, best be safe for now.

**Comment by sebastiansam55** [comment]
Only tested the async/threads enter/leave on gtk as you can probably guess from the commits lol. 

I tested the original changes on both, just don't have qt setup currently.

**Comment by BlueDrink9** [comment]
Do you know how to fixup commits? `git rebase -i 5e5fe88c26943a2fb5fe26b7a0c926c8d0683c9c`, then change that last commit to a `fixup` instead of `pick`. Then force push back to the branch. Just keeps the commit history tidier.

Creating the changelog made me realise just how messy the history is atm.

**Comment by BlueDrink9** [comment]
> > I should also wrap the gtk version in the gdk enter threads like the other ones, I had no issues in briefly testing it but there is probably a reason the other methods wrap like that
> 
> I too would like to know what they do. I found some inconsistencies that seemed not to have mattered while doing refactors, so I suspect it may be a case of monkey see = do in some places. Still, best be safe for now.

Also at least one instance generated a deprecation warning, so it may be that it used to be an issue but is not anymore.

**Comment by sebastiansam55** [comment]
> Do you know how to fixup commits? `git rebase -i 5e5fe88c26943a2fb5fe26b7a0c926c8d0683c9c`, then change that last commit to a `fixup` instead of `pick`. Then force push back to the branch. Just keeps the commit history tidier.
> 
> Creating the changelog made me realise just how messy the history is atm.

Not at all, I am vaguely aware that it is possible to delete commits if you accidentally commit a password or something but it's a bit over my head. I'll work on it!

Is there anything else this needs before merge?

**Comment by BlueDrink9** [comment]
Nope, otherwise fine. If you want I can sqaush those two commits myself, but I thought I'd give you the learning experience. Do you use a git gui?

Basically I don't want commits that fix previous commits in the same PR. They should be squashed as a single commit

**Review by BlueDrink9 — APPROVED** [review]

**Pull request merged**
