### PR TITLE
 Upgrade develop branch to work with ubuntu-latest.

### PR DESCRIPTION
**Pull request by Elliria**
Corrected passenv error.

### CODE REVIEW

**Comment by Elliria** [comment]
I think **master** needs **xhost**. PR #788 should fix it if you merge that one in first.

**Comment by Elliria** [comment]
Before I scrap this pull request and do another one to see if the change to **master** that just happened fixed it, it's possible we'll still have this error that's in one of the red x marks above:
```
FAILED tests/UIs/test_headless.py::test_application_runs_without_errors - Fil...
============ 1 failed, 390 passed, 8 skipped, 13 xfailed in 13.29s =============
ERROR: InvocationError for command /home/runner/work/autokey/autokey/.tox/coverage/bin/pytest --cov=/home/runner/work/autokey/autokey/.tox/coverage/lib/python3.7/site-packages/autokey --cov-append (exited with code 1)
```
Is it possible that it's happening because we don't have a **tox.ini** file? From what I've been able to find out online:
* The **setup. cfg** and **setup.py** files are for building distributions.
* The **tox. ini** file is for running tests in virtual environments that are created on-the-fly.

**Comment by userdocs** [comment]
I am pretty sure that error was specific to that commit. You fixed it, pushed the changes and the test passed.

If the tests are passing, just merge this. It's working.

**Comment by Elliria** [comment]
In other words, the red x marks above don't matter as long as it says "All checks have passed" and "This branch has no conflicts with the base branch"?

**Comment by userdocs** [comment]
The tests are running on push so if it fails you push the fix, it works, and so on. As you see my PR has no test until you merged it.

These previous tests are not blockers to merging. You pushed, it failed, you pushed a fix, it succeeded.   The PR test checks passed. 

Really, it's a simple merge now. Essentially, stop playing with it, merge it and go next.

**Comment by Elliria** [comment]
I think I understand it now. The top ones (that have the red x marks in them) are commit tests, whereas the ones down here at the bottom (with the green check-marks) are PR tests. In that case, as you pointed out, all is well. It's so nice to finally understand it. I can't merge it, but @josephj11 or @BlueDrink9 will be along at some point.

**Comment by josephj11** [comment]
Merged. Got all green check marks!

**Pull request merged**
