### PR TITLE
Typo - Added missing space

### PR DESCRIPTION
**Pull request by denis-roy**
Commit is self-explanatory :)

And while I have your attention: Keep up the great work! :+1:

### CODE REVIEW

**Comment by josephj11** [comment]
Looks OK to me, but it needs to be applied to the develop branch or it may be lost in 0.96. We also need to check if it needs fixing in the Qt front end.

**Comment by BlueDrink9** [comment]
What Joe said about the `develop` branch. But don't worry about it, I'll sort it when I get a chance. Same re: the QT issue. I'll leave this PR open until as a reminder, then I'll accept it.

**Comment by denis-roy** [comment]
Here is the PR for `develop` -> #525

**Comment by josephj11** [comment]
Replaced by #525

**Pull request closed without merging**
