### PR TITLE
Large refactoring of non-UI code

### PR DESCRIPTION
**Pull request by BlueDrink9**
Sweeping code deduplications and refactoring across core non-UI files. Will probably need beta testing before merging, but once finished will make it much easier to understand the codebase.

Based off #499

### CODE REVIEW

**Comment by BlueDrink9** [comment]
Something to be wary of when reviewing is where a function has been extracted that takes an argument, but doesn't return it after acting on it. I suspect they may be areas where I have inadvertantly changed code behavior.

**Comment by josephj11** [comment]
How many commits is too many for one PR? Real question - not an opinion.

**Comment by BlueDrink9** [comment]
In reality this is way too big. But I don't really know how to change that. It refactors so many files, but the act of 'refactoring' is a single PR to me. It'll just need lots of testing. At minimum, I plan on getting a high test 'coverage' without actually testing behaviour, just checking the code paths for errors.

Admittedly, this is based off a couple of my existing PRs, so the commit list currently includes them. If they get reviewed and accepted, this commit list will shrink.

But actually yes, looking at this list there is a lot that could be separated out into separate PRs, I think. Also plenty of commits that could be merged. I'll tidy it once it's closer to ready for merge

**Comment by BlueDrink9** [comment]
This PR is scaring new contributors so I'll close it until I have time to work on it more. I'll sort out any conflicts if changes get merged to develop before this does.

**Pull request closed without merging**
