### PR TITLE
Gnome window interface. Configurable UInput delay

### PR DESCRIPTION
**Pull request by sebastiansam55**

### CODE REVIEW

**Comment by Elliria** [comment]
Hey there, I figured I'd test the **Develop** branch to see how it runs in **Kubuntu 22.04 LTS**, which doesn't yet use Wayland, to see what would happen. When I try to clone AutoKey and run it, I get the notifications below and AutoKey won't start.

## The steps Steps I followed to clone and test the Develop branch of AutoKey:

1. Clone the Develop branch:
	```
	git clone --branch develop --single-branch https://github.com/autokey/autokey.git
	```
2. Change to the autokey sub-directory you just created:
	```
	cd autokey
	```
3. Change to the lib sub-directory:
	```
	cd lib
	```
4. Pick one:
	* Run AutoKey GTK:
	```
		python3 -m autokey.gtkui -lc
	```
	* Run AutoKey Qt:
	```
		python3 -m autokey.qtui -lc
	```
5. Interact with the error notifications as described below.

## The results

### AutoKey GTK
When I try to run AutoKey GTK, I get this notification:



When I click the **OK** button, I get this notification:



When I click the **OK** button, the notification closes and AutoKey doesn't start.

### AutoKey QT
When I try to run AutoKey Qt, I get this notification:



When I click the **Show Details...** button, I get these details:



When I click the **OK** button, I get this notification:



When I click the **Show Details...** button, I get these details:



When I click the **OK** button, the notification closes and AutoKey doesn't start.

## The AutoKey log
Here's a copy of the AutoKey log with verbose logging enabled: [autokey.log](https://github.com/user-attachments/files/17120538/autokey.log)

**Comment by sebastiansam55** [comment]
can you post the autokey log? this can happen if it's unable to grab the mouse/keyboard.

**Comment by Elliria** [comment]
It's already there at the bottom of my message just above yours.

**Comment by Elliria** [comment]
I thought I'd add that I followed the above test by cloning **Master** and repeating the test and was able to successfully run **AutoKey GTK** and **AutoKey Qt** with no issues.

**Comment by sebastiansam55** [comment]
for the moment the develop branch should be considered wayland only. I have not tested the branch on x11

**Comment by Elliria** [comment]
Ah, okay. Those were X11 tests, but those can provide useful information, so it might not be a bad idea to continue doing them after merges.

**Pull request merged**
