### PR TITLE
Update engine.py

### PR DESCRIPTION
**Pull request by sebastiansam55**
Change default sendmode for engine.create_phrase to CB_CTRL_V

### CODE REVIEW

**Comment by josephj11** [comment]
Note: This is for consistency with #520 which makes the same change in the GUI.

**Comment by BlueDrink9** [comment]
As mentioned in the Gitter, IMO this is not a good idea. Whereas changing the GUI only applies to new phrases, the scripting API is often used to more easily recreate previous scripts; meaning this change may break existing setups.

**Comment by josephj11** [comment]
@BlueDrink9 As usual, I am not merging this now, but I would like to understand your use case better - on Gitter, etc.

I don't like the inconsistency between the GUI and this API, but anyone sophisticated enough to use this API at all should be able to deal with it with no problem.

At a minimum, I would like something added to the documentation pointing out the difference between the two. (And that would probably involve regenerating the API documentation which, last I saw, was something we were still figuring out how to do in the Python 3 branch of AutoKey.)

I definitely want to keep the GUI version change as that will avoid a lot of end user issues.

**Comment by BlueDrink9** [comment]
> At a minimum, I would like something added to the documentation pointing out the difference between the two. (And that would probably involve regenerating the API documentation which, last I saw, was something we were still figuring out how to do in the Python 3 branch of AutoKey.)

TBH considering how many other changes 0.96 will bring, I think this is a reasonable solution. I'll push a note to the changelog

> I definitely want to keep the GUI version change as that will avoid a lot of end user issues.

Oh absolutely, definitely agree the GUI version is good.

**Pull request merged**
