### PR TITLE
Preparing wayland support changes

### PR DESCRIPTION
**Pull request by promisingcoder**

### CODE REVIEW

**Comment by dlk3** [comment]
@promisingcoder:  What version of the pywayland Python module are you using?  I tried to test this PR but it failed while importing that module.  My distribution (Fedora 40) delivers pywayland 0.4.17 and I also tried the latest version from PyPI, version 0.4.18.  Both of those failed with ```cannot import name 'wl_seat' from 'pywayland.protocol'```  I looked at the latest docs for [pywayland](https://pywayland.readthedocs.io/en/latest/module/protocol/wayland.html#wlseat) and there is a pywayland.protocol.wayland.WlSeat object in there but no pywayland.protocol.wl_seat that I could find.  Maybe you're using a different version of pywayland than I am or something??
```
$ autokey-gtk -l
Traceback (most recent call last):
  File "/home/dlk/src/autokey/autokey-test/bin/autokey-gtk", line 5, in <module>
    from autokey.gtkui.__main__ import main
  File "/home/dlk/src/autokey/autokey-test/lib64/python3.12/site-packages/autokey/gtkui/__main__.py", line 5, in <module>
    from autokey.gtkapp import Application
  File "/home/dlk/src/autokey/autokey-test/lib64/python3.12/site-packages/autokey/gtkapp.py", line 39, in <module>
    from autokey import service, monitor
  File "/home/dlk/src/autokey/autokey-test/lib64/python3.12/site-packages/autokey/service.py", line 35, in <module>
    from autokey.iomediator.io_mediator_wayland import IoMediatorWayland
  File "/home/dlk/src/autokey/autokey-test/lib64/python3.12/site-packages/autokey/iomediator/io_mediator_wayland.py", line 2, in <module>
    from autokey.iomediator.interface_wayland import IoInterfaceWayland
  File "/home/dlk/src/autokey/autokey-test/lib64/python3.12/site-packages/autokey/iomediator/interface_wayland.py", line 2, in <module>
    from pywayland.protocol import wl_seat
ImportError: cannot import name 'wl_seat' from 'pywayland.protocol' (/home/dlk/src/autokey/autokey-test/lib64/python3.12/site-packages/pywayland/protocol/__init__.py)
```

**Comment by josephj11** [comment]
@dlk3 This PR has a huge set of changes from someone who hasn't communicated with us at all. The last one like this was AI generated garbage attempting to get a bounty for free. I can't imagine anyone manually coding such a massive change without first communicating with us.

This  one doesn't look particularly promissing because it's based on master and ignores all the work already done in develop.  That's a huge red flag.

I haven't looked at the code at all yet and would love to proven wrong, but I suspect there would be some communication with us about what was accomplished and what wasn't. I am fairly sure there is at least one feature that can't be fixed.

**Comment by Elliria** [comment]
I'm concerned about this one for the same reasons and it's also beyond my ability to analyze.

**Comment by dlk3** [comment]
I have the same concerns that you guys do, but I have read the code and there are changes in it that could make sense.  I thought I'd give the coder the benefit of the doubt.  Now however, given that they aren't communicating, I'm wondering if this isn't a fake, as you say.

**Comment by Elliria** [comment]
I've got one other concern that there are 147 files that were changed and it all happened in one huge commit. You'd think there would be 147 commits inside one pull request instead.

**Comment by dlk3** [comment]
Yeah I saw that.  I have no idea how github came up with that number, there aren't actually that many changed files in the PR.  Maybe some quirk in the way the PR was submitted??  I haven't bothered to dig into that.  It'd be trivial, if the code worked.

Have you looked at the coder's profile on github?  Based on their activity it looks like they're a real person to me, or that someone has gone to a lot of trouble to make it look like they are.

I'd think we'd want to be grateful to anyone who tries to help out and give them the benefit of the doubt rather than jump right to calling them a fake without even having taken a proper look at the code they submitted.  If a project did that to me, I know I'd be quick to move on to projects that were a bit more welcoming.

**Comment by Elliria** [comment]
I think it's a coding style, with one person preferring lots of commits and another preferring several related changes in one commit. I did look at the profile and it seems to be legitimate. I'm not qualified to dig through all that code and understand it, though. @sebastiansam55 understands Wayland code. Hopefully he'll take a look at it. If this solves our Wayland issue, we'll be eternally grateful to @promisingcoder for the help.

**Comment by dlk3** [comment]
Ok, I dug deeper into the code and this probably isn't fake but it isn't complete either.  It should be closed, in my opinion, with instructions to resubmit when it is complete.

As an example, looking at the ```lib/autokey/iomediator/interface_wayland.py``` file in the PR I see that the ```handle_key_event()```, ```send_string()```, and ```send_keys()``` functions are all incomplete stub functions.

As to the 147 changed files question, there are only 6 new/changed files in the PR that matter.  The rest are extraneous files included from the ```build``` directory that were created during testing and a couple extra copies of the program icon files.  I'd be willing to bet that these files were included in the commit that is the basis of this PR due to a developer mistake or misunderstanding.  That should all be cleaned up in any subsequent submission.

**Comment by dlk3** [comment]
This patch file contains the actual code changes that are made in this PR, in the 6 new/changed files I mentioned above.  It may be pointless, but since I went to the trouble to extract this, I thought I'd archive it here.

[patch.txt](https://github.com/user-attachments/files/18117730/patch.txt)

**Comment by josephj11** [comment]
I'm not going to close this yet. If @promisingcoder is willing to communicate with us and discuss their changes and rebasing them on develop..., then great.

If there are stubs in the code as @dlk3 has found, then it clearly needs work. However, there's no point in debugging/testing it unless the developer is actively engaging with us.

**Comment by Technetium1** [comment]
Looking at mostly just @dlk3's distilled changes, it doesn't seem like anything much more substantive than ChatGPT would potentially spit out. I'm highly skeptical of the legitimacy of this. Why not PyQt6? Why no communication? Look at their other recent pull requests to claim bounties versus their personal projects...

**Comment by josephj11** [comment]
Welcome to the AutoKey community, @Technetium1 !  (hope I haven't missed earlier posts by you.)

You're probably right. We'll wait a little longer to see if the OP responds.

If we are really seeing a wave of bounty harvesting attempts, that really tics me off. We're severely short on dev resources to start with. We don't need code spam on top of that.

I like that "pacman" worm on your GitHub page. It took me a moment to figure out what it was. :)

**Comment by Elliria** [comment]
Thank you for looking this over, @dlk3 and @Technetium1. How did you manage to distill those 143 changes into that tiny little patch, @dlk3?

I took a look at the patch and here's my take on it, for what it's worth:
* I don't know enough to be comfortable analyzing `interface_wayland.py`.
* I don't know enough to be comfortable analyzing `io_mediator_wayland.py`.
* `common.py` looks good.
* `engine.py` looks good.
* `service.py` looks good.
* `setup.py` looks good.

**Comment by Technetium1** [comment]
@Elliria I didn't look _only_ at the distilled changes. Here's a simple thing to point out, how would a human add a lock and not know _why_ they added it? https://github.com/autokey/autokey/pull/990/files#diff-0ed7b9180fcf26ed2cc9e3cf62c2efb6e3b962b30c895b62dd47e39b82be4659R23
```py
SEND_LOCK = threading.Lock()  # TODO: This is never accessed anywhere. Does creating this lock do anything?
```
It's also hard to convince me that this logger: https://github.com/autokey/autokey/pull/990/files#diff-39b967a443f5950a8b9f454c864eebcf4491dbcfbf8d9d5bd1f00e539d2dd683R60
```py
    if args.cutelog_integration:
        socket_handler = logging.handlers.SocketHandler("127.0.0.1", 19996)  # default listening address
        root_logger.addHandler(socket_handler)
        root_logger.info(f"""Connected logger "{root_logger.name}" to local log server.""")
```

was not taken as boilerplate from https://github.com/luziferius/av1transcoder/commit/19ba2a148033f6db9d27c4033097d14d6526b65e#diff-0a4807a3ccd4bde7086d3d80241bf34215ceaf0ad0b7d711e4538001c2c8dafcR31:
```py
    if args.cutelog_integration:
        socket_handler = logging.handlers.SocketHandler("127.0.0.1", 19996)  # default listening address
        root_logger.addHandler(socket_handler)
        root_logger.info(f"""Connected logger "{root_logger.name}" to local log server.""")
```

---

@josephj11 Thanks! You haven't missed anything from me. I'm a silent watcher for a lot of projects. I don't generally speak out unless there is an issue, which I see this as. I don't have a problem with AI assisting people, but it's unacceptable to give it full control rather than augmenting an already capable developer.

**Comment by josephj11** [comment]
@Technetium1  I  have started using AI to help figure out how to do things. It solved a bash probem for me the other day. I use it for research, not for final code. If you don't know enough to code it yourself, there's a pretty good chance you won't spot the errors and omissions that are so common in LLM outputs.

In ay case, I'm glad you're here!

**Comment by Elliria** [comment]
Good points on the lock and logger, @Technetium1. I'm glad you're looking this stuff over.

**Pull request closed without merging**
