### PR TITLE
Remove executable permission from included SVG files

### PR DESCRIPTION
**Pull request by anthonyfok**
Dear maintainers,

For some reasons, 6 of the SVG files have the executable bit set (permission 100755) for quite some years, and the debian/rules in the old Debian packaging had a `override_dh_fixperms` target to fix the file permission:

    chmod a-x debian/autokey-common/usr/share/icons/*/*/*/*.svg

This pull request aims to make that old workaround unnecessary.

By the way, thank you very much for keeping the Debian packaging files (debian/*) up-to-date, which has been tremendously helpful in finally upgrading the autokey package in the Debian repository:

* https://salsa.debian.org/python-team/applications/autokey
* https://tracker.debian.org/pkg/autokey (pending update)

### CODE REVIEW

**Comment by luziferius** [comment]
How did _that_ go unnoticed? Hmmm…
Thank you for raising the issue and fixing it directly!

**Comment by luziferius** [comment]
@anthonyfok If there is anything we can adjust on our side to bring our `debian` control files in line with the ones used by the Debian project, please say so. This will reduce the patch sizes on your side and increase the packaging quality for everyone.

**Comment by josephj11** [comment]
@anthonyfok Thank you so much for packaging the current AutoKey for Debian! Aside from preventing it from being completely deleted from ongoing Debian repositories, I can't tell you how many bug reports and support requests we've had to deal with where the answer was, "get the new version."!

**Comment by anthonyfok** [comment]
@josephj11 You are very welcome.  It was a happy coincidence as I was searching for a tool for keyboard and mouse automation, and eventually came upon AutoKey and noticed its state in Debian, etc.  I have yet to learn how to use AutoKey itself, but I'm sure AutoKey will help me save me from some manual repetitive tasks in the future!  For that I thank you very much!  :-)

**Comment by anthonyfok** [comment]
> @anthonyfok If there is anything we can adjust on our side to bring our `debian` control files in line with the ones used by the Debian project, please say so. This will reduce the patch sizes on your side and increase the packaging quality for everyone.

For future reference: the discussion continued at #364

**Pull request merged**
