### PR TITLE
Add alt_gr as an option when setting hotkeys

### PR DESCRIPTION
**Pull request by sebastiansam55**
Tested using `xmodmap` to remap rightmeta to `ISO_Level3_Shift` (`AltGr`). Fix for #366. Picture of change in UI attached. Works as expected in combination with other modifier keys.

Screenshot from 2020-11-20 08-06-30

### CODE REVIEW

**Comment by johannesjo** [comment]
If somebody can provide me with build instructions I can offer to test this!

**Comment by sebastiansam55** [comment]
@johannesjo 
```
git clone --branch develop_altgr https://github.com/sebastiansam55/autokey.git
cd autokey/lib
python3 -m autokey.gtkui -l
```
Ought to do it.

**Comment by johannesjo** [comment]
Works like a charme! Thank you very much @sebastiansam55 !!

**Comment by sebastiansam55** [comment]
No problem, keep in mind that that is from the develop branch on my fork of the project, if this PR gets accepted I'd recommend you basically just switch the first line to
`git clone --branch develop https://github.com/autokey/autokey.git`
So you'll have the "official" development version.

Hopefully we'll get a new main branch release some time soon tho.

**Comment by lnksz** [comment]
Thanks @sebastiansam55!
I checked out your branch too, and it does work as expected.

Hopefully a maintainer will pick this up.

**Comment by lnksz** [comment]
Hi there,
this is a great feature! Any plans to merge it to master/release it?

**Comment by josephj11** [comment]
It looks like this got merged into develop before 0.96 was released, so I don't know why I don't see it in AutoKey.

I don't think I have that key on my keyboard. I'm not familiar with it although I have seen references to it many times.

I poked around. It is implemented and working in 0.96.0, our current release, but note that this enhancement was only added to our GTK front end. AFAIK, a similar enhancement was not made to our Qt front end.

@lnksz If you are not already using 0.96.0, you can get it [here](https://github.com/autokey/autokey/releases/) with installation instructions [here](https://github.com/autokey/autokey/wiki/Installing).

I highly recommend upgrading because 0.96.0 has a lot of bug fixes and several enhancements and that's where any further bug fixes/enhancements will be applied.

**Comment by lnksz** [comment]
Hi @josephj11,

I use 0.96.0 through the AUR package. But used it with the Qt GUI. I installed the GTK version and the menu is there and works as expected!

Sorry for the noise!

But is was it known that the qtui is lagging behind in this feature?
https://github.com/autokey/autokey/blob/fbcc72b8d9b6d87c0c49520eef7e0abef3750177/lib/autokey/qtui/dialogs/hotkeysettings.py#L68

**Comment by josephj11** [comment]
We have very limited developer resources, so  we don't complain when we get an improvement, but it really should be added to the Qt side as well.

Feel free to join us on [Gitter](https://gitter.im/autokey/autokey) if you have any other questions/suggestions that don't feel like they rise to the level of an issue or just want to interact with other users.

**Comment by lnksz** [comment]
Hey, then it is even more impressive how good AutoKey is. The Qt part sounds like a fun task I would happy to give a go

**Comment by josephj11** [comment]
@lnksz Great! Gitter is the place if you need any guidance. PRs should be based on our develop branch. See [this](https://github.com/autokey/autokey/blob/master/CONTRIBUTORS.rst)

If you are interested, we also have a few other issues tagged as easy fix or good first issue, but you can contribute with anything you want to work on..

If you have new  enhancement ideas, it's a good idea to discuss them on Gitter first, so you'll know whether they are likely to be accepted before putting in all the development work.

**Pull request merged**
