### PR TITLE
Update README.rst - badges, formatting, wording, links, and info.

### PR DESCRIPTION
**Pull request by Elliria**
- Update IRC badge to Libera.Chat.
- Add CodeTriage badge to satisfy issue #779.
- Formatting.
- Wording.
- Update IRC information.
- Update troubleshooting information.
- Move pull request mention to the "Contributing or modifying the source" section.
- Add CodeTriage information to the "Contributing or modifying the source" section.
- Fix broken links.
- Fix displayed CONTRIBUTORS.rst link.
- Change **master** links to **develop** links.

### CODE REVIEW

**Comment by Elliria** [comment]
Please merge this in to update [the **develop** branch's README.rst file](https://github.com/autokey/autokey/blob/develop/README.rst), @josephj11. It needed quite a few changes.

Would you like me to make similar updates to [the **master** branch's README.rst file](https://github.com/autokey/autokey/blob/master/README.rst)? My thoughts are:

* [The **master** branch's README.rst file](https://github.com/autokey/autokey/blob/master/README.rst) is the first file visitors are presented with when they go to [the AutoKey main page on GitHub](https://github.com/autokey/autokey) and if you compare it with the one I just changed, it has quite a bit of misinformation in it.
* If anyone comes along and would like to contribute, they won't necessarily know right away that we prefer developers to do pull requests on the **develop** branch, so they may go poking around in the wrong branch and not realize that some things have already changed.

And the same question goes for [the **beta** branch's README.rst file](https://github.com/autokey/autokey/blob/beta/README.rst), since that one also contains the same misinformation and needs the same updates.

**Comment by josephj11** [comment]
I see no point in pushing any updates to beta except, maybe, GitHub actions and other infrastructure changes that are best done when the details are all still at the fore.

I will merge them if you do them. I just think your time is better spent on other things.

If you want to, it might not be a bad idea to modify the README.rst on beta to prominently say this branch is currently inactive and dated. It is only relevant when a new release is pending.

I'll take another look at this after I merge it so I can see the new version. I suspect updating it on master is a good idea.

**Comment by josephj11** [comment]
Things I missed:

```
Important: This is an X11 application, and as such, will not function 100% on distributions that default to using Wayland instead of Xorg.
```

would be better as

```
Important: This is an X11 application, and as such, will not function correctly when Wayland is in use instead of Xorg.
```

Also, why do we reference unit tests here at all? The paragraph above that includes them in the provided link.

**Comment by Elliria** [comment]
> I see no point in pushing any updates to beta except, maybe, GitHub actions and other infrastructure changes that are best done when the details are all still at the fore.

Okay, although I'd love a list of the "other infrastructure changes" so I'll know them if I see them.
 
> I will merge them if you do them. I just think your time is better spent on other things.

I'll try to avoid doing them from now on except for things like the one mentioned below.
 
> If you want to, it might not be a bad idea to modify the README.rst on beta to prominently say this branch is currently inactive and dated. It is only relevant when a new release is pending.

Should I leave the rest of the document as is and just lead with that or would you rather I replace its contents with that?
 
> I'll take another look at this after I merge it so I can see the new version. I suspect updating it on master is a good idea.

Okay, let me know what you think after taking a look. It wouldn't take me long to do it and none of it directly references the version, so it shouldn't do any harm.

**Comment by josephj11** [comment]
Whenever we stub our toes or trip on something, we'll make a note of it. I didn't want to be overly specific.

Replacing beta README.rst: When we make a new beta, we'll probably clear it out and copy develop (or another branch) to it, so it really doesn't need to have anything in it now as long as the setup stuff we just suffered through doesn't have to be redone from scratch. If recreating/copying/configuring is really easy, I would lean toward deleting the whole branch, but if it's not...

So whatever you think is easiest. For now, it's essentially dead code, so if it's there, it should be clear to visitors that this isn't a glimpse into the future, etc.

**Comment by Elliria** [comment]
> ```
> Important: This is an X11 application, and as such, will not function correctly when Wayland is in use instead of Xorg.
> ```

Agreed, and it looks like I forgot to fix the placement of the first comma, so I'll do that as well.
 
> Also, why do we reference unit tests here at all? The paragraph above that includes them in the provided link.

Probably because people who don't wish to contribute to the project may also wish to run unit tests, especially if they're downloading the zip file of the code that's in development or installing it with pip and then running that version of AutoKey on their systems. Package maintainers might also wish to know how to do the tests.

Note that our instructions for unit tests in the [README.rst file](https://github.com/autokey/autokey/blob/master/README.rst) on the **master** branch are completely outdated, but that will be taken care of if I do the same update to that file as I just did to this one, since it simply points to the **CONTRIBUTORS.rst** file for instructions.

**Comment by Elliria** [comment]
> Replacing beta README.rst: When we make a new beta, we'll probably clear it out and copy develop (or another branch) to it, so it really doesn't need to have anything in it now as long as the setup stuff we just suffered through doesn't have to be redone from scratch. If recreating/copying/configuring is really easy, I would lean toward deleting the whole branch, but if it's not...

I'm not sure if the actions would have to be manually recreated. The code definitely gets copied over completely whenever any branch is created.
 
> So whatever you think is easiest. For now, it's essentially dead code, so if it's there, it should be clear to visitors that this isn't a glimpse into the future, etc.

I just took a look at the [beta branch](https://github.com/autokey/autokey/tree/beta) and since the 12 commits it had that **master** didn't were by me, I suspect that the whole thing can safely be scrapped.

**Comment by josephj11** [comment]
>Probably because people who don't wish to contribute to the project may also wish to run unit tests, especially if they're downloading the zip file of the code that's in development or installing it with pip and then running that version of AutoKey on their systems. Package maintainers might also wish to know how to do the tests.

Good points. I'd still like to have it in one place, so a note about it being in CONTRBUTORS.rst would be good,

**Comment by josephj11** [comment]
As long as you can just copy the most recent release candidate branch to a new beta branch and have it "just work" without changing a bunch of labels/links/parameters, then I'm all for deleting the beta branch.

(The release candidate branches start out as a copy of develop with anything that's not ready for release removed - which means that there needs to be an easy way to know what to remove and to remove it. Maybe there's some way to "tag" some PRs as "approved"/"included" and/or others as "under development"/"unapproved".)

**Comment by Elliria** [comment]
> I'd still like to have it in one place, so a note about it being in CONTRBUTORS.rst would be good,

That's what we currently have in the [README.rst](https://github.com/autokey/autokey/blob/develop/README.rst) file in the **develop** branch. Does that one look okay to you? It is a bit awkward that **CONTRIBUTORS.rst** is linked to twice very close together in that document, but we could get around that by alphabetizing the headings in the document if you like.

**Comment by Elliria** [comment]
> As long as you can just copy the most recent release candidate branch to a new beta branch and have it "just work" without changing a bunch of labels/links/parameters, then I'm all for deleting the beta branch.

I checked in the **##github channel** on IRC and @userdocs happened to be on and said that everything is copied over automatically.

> (The release candidate branches start out as a copy of develop with anything that's not ready for release removed - which means that there needs to be an easy way to know what to remove and to remove it. Maybe there's some way to "tag" some PRs as "approved"/"included" and/or others as "under development"/"unapproved".)

I'm not sure how something like that would be handled. Code can affect other code, so there's no knowing that something you green-light today might not be better off red-flagged tomorrow and vice-versa. I think when it comes time to get ready for a new release, there's just a whole heck of a lot of work that has to go into taking stock and deciding what goes and what stays. No idea, though. I guess we'll find out.

**Comment by josephj11** [comment]
> > I'd still like to have it in one place, so a note about it being in CONTRBUTORS.rst would be good,
> 
> That's what we currently have in the [README.rst](https://github.com/autokey/autokey/blob/develop/README.rst) file in the **develop** branch. Does that one look okay to you? It is a bit awkward that **CONTRIBUTORS.rst** is linked to twice very close together in that document, but we could get around that by alphabetizing the headings in the document if you like.

I'm fine with it as it is, but am open to any improvements you may suggest. The topics should be in order of importance, logical flow, so alphabetizing them,  etc. probably wouldn't be a good idea.

**Comment by josephj11** [comment]
> > As long as you can just copy the most recent release candidate branch to a new beta branch and have it "just work" without changing a bunch of labels/links/parameters, then I'm all for deleting the beta branch.
> 
> I checked in the **##github channel** on IRC and @userdocs happened to be on and said that everything is copied over automatically.
> 

Great! Then I will delete the beta branch one of these days - as soon as I'm sure no one objects to doing that.

> > (The release candidate branches start out as a copy of develop with anything that's not ready for release removed - which means that there needs to be an easy way to know what to remove and to remove it. Maybe there's some way to "tag" some PRs as "approved"/"included" and/or others as "under development"/"unapproved".)
> 
> I'm not sure how something like that would be handled. Code can affect other code, so there's no knowing that something you green-light today might not be better off red-flagged tomorrow and vice-versa. I think when it comes time to get ready for a new release, there's just a whole heck of a lot of work that has to go into taking stock and deciding what goes and what stays. No idea, though. I guess we'll find out.

If there's no "reasonable" way to do it automatically, it could be done manually with something as simple as including comments in the source code that state something like "for inclusion in the next minor release",  "for inclusion in the next major release", "under development", etc.

These would have to be manually dealt with by staring at the code, etc., but would probably save time by allowing developers to know what to do  at a glance without having to analyse/research the code itself.

They would have to be manually kept up to date and deleted before actually being released, but any errors with this are still errors in a comment that don't affect anything else. And, that's why we test things and QA them before releasing them in production. There are a lot of moving parts and running the whole thing is the best way to find any mistakes that other testing missed.

**Comment by Elliria** [comment]
Probably the easiest and least-labor-intensive way to handle it would be for any minor changes to be made to **master** immediately, which is how we're currently doing things, and for any major changes that are experimental that are liked to be added to a list in an issue that has the express purpose of being a last-minute location to look for any new features that shouldn't be forgotten when doing a new release. If we put it into comments in the code, they'll be buried/ignored/overlooked/forgotten, etc. My two cents. I'll defer to whatever is decided, though, but would love input on this from seasoned coders who know what the best practices for such things are.

If I understand how the branches work:
* **master** is the current stable code that prefers to be left alone
* **master** sometimes gets minor solid stuff from **develop**
* **develop** is play-land where anything goes
* **develop** keeps up with and gets ahead of **master**
* **beta** is pre-release for only the good minor or major stuff from **develop**
* **beta** keeps up with and gets ahead of **master**
* **beta** becomes **master** and the new release once it reaches certain goals or is loved and solid

I'm guessing, though. Feedback is always appreciated.

**Comment by josephj11** [comment]
IMHO, master should never be updated. It should only be replaced with a new master upon release. Exceptions to this should only be things like updating typos in comments or adding new standalone files like a code of conduct or new example code that doesn't modify any existing files and doesn't affect the program's operation in any way. If some text displayed in the GUI has a typo, that would be OK too.

As soon as you open master to functional updates, line numbers change and there is no common uderstanding of what release 0.x.x actually is without the exact date the whole release was last modified. I can remember most of what is in a release. but I can't begin to remember multiple subversions by date.

If someone reports a bug, one of the first steps is usually to recreate it, both for analysis and to verify that it's not the result of something local to the OP's system. If we test and cannot recreate, then the bug is usulally dismissed as an AutoKey problem and becomes a user problem. Getting a false negative is bad because a bug is likely to be ignored. When we test against code that is not verifiably identical to the OP's code, it  greatly undermines our ability to trust the results. This opens a rather large can of worms that I would greatly prefer to avoid.

Compiled or packaged systems often come with a checksum which, when verified, assures that not a single byte has been altered. When you're dealing with an interpreter and a loose collection of files, there is no checksum (except to a whole zip archive). And once the application has run some other things change that invalidate a checksum.

**Comment by Elliria** [comment]
We've been making only minor updates to **master** so far. Nothing that has to do with new features or anything big.

I believe you can go into the history of the repository and pull up releases by their tags and look at their code that way. Releases and/or their source code can also be downloaded from our [Releases](https://github.com/autokey/autokey/releases/) page. Either way, they're independent of the **master** branch for the most part in that they're only the **master** momentarily and once they're tagged, **master** can move on.

As for the checksums, our releases don't change once they've been created, so those shouldn't be a concern and should be rock-solid. All the rest of the code is up for grabs in a constant state of flux, though - even **master**.

I looked into branching strategies today. Apparently, the two most popular ones are the [GitHub Flow](https://docs.github.com/en/get-started/quickstart/github-flow) and the [Git Flow](http://danielkummer.github.io/git-flow-cheatsheet/). It looks like we're using a modified Git Flow. It seems that your branching strategy can be as much an art as making a burger.

**Comment by josephj11** [comment]
I guesss I'm being too fanatic. As long as we get a correct answer from the user as to exactly where they got our code from, we should be OK. I'd still like to keep changes to the main branch minimal, but some are OK.

**Comment by Elliria** [comment]
No worries. We're both trying to figure this thing out and I agree with you that changes to the **master** branch should be minimal.

**Comment by Elliria** [comment]
Would you like the [README.rst](https://github.com/autokey/autokey/blob/master/README.rst) file on **master** to be updated the same way as this [README.rst](https://github.com/autokey/autokey/blob/develop/README.rst) file on **develop** was? It has the same issues and is the first document that a user encounters when they come to our repository.

If so, I'm not sure if you'd like me to just delete the contents of the one in **master** and paste the contents of the one in **develop** into it or if there's some voodoo you can do at your end with an administrative merge or rebase or whatever is called for in such cases.

**Comment by josephj11** [comment]
Again, any changes to main are not the best idea, but this one is a standalone file (as long as none of the embedded links are branch specific, etc.), so it may be worth doing.

It's a choice. If we do it by brute force replacement, it would certainly work, but putting my git propeller beanie on, I realize that that change would have no history which is probably not the best idea.

Theoretically, you should be able to do it with a simple PR from the new version onto the old one exactly the same as you have done with your other changes to main.

**Comment by Elliria** [comment]
Believe it or not, I have no idea how that's done. I know how to do a PR for files that I've changed, but not for files that already exist and haven't changed. You wouldn't happen to know how I'd do that, would you?

**Comment by josephj11** [comment]
Clues only. I think you take the PR you just did on develop. Since it's all based on line numbers, it has to be rebased to line up with master. Now you have a "new" PR on master just like any other PR.
The trick is reviewing what the rebasing did and making sure that everything is compatible with the master environment..

**Comment by Elliria** [comment]
I guess that would have to happen at your end, because I don't have any offers for things that I'm able to do when I view a closed PR.

**Comment by josephj11** [comment]
I don't think it directly involves the closed PR, but I'm not sure. We have had several outside PRs based on master and they were asked to rebase them on develop and resubmit them, so there is a common way to do it. @BlueDrink9 or @sebastiansam55 probably know how it works.

**Comment by Elliria** [comment]
Okay. Hopefully either one of them will chime in here or I'll end up learning how it's done.

**Pull request merged**
