### PR TITLE
issue337 don't use dot files

### PR DESCRIPTION
**Pull request by xpusostomos**
A fix for issue 337: Stop hiding the sidecar files for phrases and scripts #337

#337

json config files no longer hidden by "." in filename.

### CODE REVIEW

**Comment by BlueDrink9** [comment]
Github tip for the future, if you explicitly state "close #337" or "fix #337" in your PR text, when it gets merged the issue will automatically be closed.

**Comment by josephj11** [comment]
I thought this required some conversion, etc. to keep current sidecar files working. Are there any legacy issues?

**Comment by BlueDrink9** [comment]
This patch includes conversion, at least from a cursory review. It probably shouldn't have been merged unless troxor reviewed it; but then we go back to our original problem.

**Comment by josephj11** [comment]
Someone please review this to make sure it was ready for prime time. As mentioned elsewhere, this will change things in user files, so we need to alert them that this is intentional. Also, several people have external scripts to generate new phrases, etc. and they'll need to know that they have to change them.

**Comment by BlueDrink9** [comment]
Any suggestions for how to alert people? Particularly for the scripting issue?

0.96 in general is going to be a huge update if/when it gets released, so it might just be a case of having a big changelog with a heading for incompatible/breaking changes.

Normally with semantic versioning we would change the major version number for such changes, but we haven't got an official 1.0 release so we can't do that.

**Comment by xpusostomos** [comment]
Autokey already has popup messages in certain circumstances. Maybe any orphan sidecars, not just these ones, should popup a message on startup.

**Comment by josephj11** [comment]
@xpusostomos Not sure what you're proposing. If someone has a few hundred
phrases and scripts, we'd certainly want only one pop-up. That's probably
what you intend. What's an orphan sidecar? One which has no corresponding
phrase or script? You might just want to ignore files like that (and
anything else that doesn't look like AutoKey files.) If I edit a script
with kate and it leaves a script.py~ file lying around, AutoKey doesn't
seem to notice. In KDE, there could also be a .desktop file lying around.

**Comment by xpusostomos** [comment]
That's a good point. I kinda think it makes sense for the files to have their own .autokey extension rather than a generic .json so that one can be sure what the files are purporting to be.

And also, if I remember right, the code organises itself according to the .py and .txt scripts, and then looks for the sidecar. But to my way of thinking, it should look for the sidecar, and if necessary look for the .py and .txt. But I guess that doesn't help the immediate problem here.

**Comment by josephj11** [comment]
Having a distinct extension and looking at them first makes sense, but there won't be anything else in those directories unless the user explicitly puts it there, so it kinda comes under the rubric of "You can't fix stupid."

The main point of however the code works is that it shouldn't produce any false negatives or false positives. If you find a sidecar with no corresponding main file, there's nothing you can do about it. It probably should just be ignored. If AutoKey starts deleting phrases and scripts by itself somehow, I'm sure we'll hear about it!

Apocrypha: Long ago and far away, I used WordMaster on my CP/M system. It was possible to insert an end of file character in the middle of your document (which would truncate it at that point - probably not what you wanted!) When you did that, the word "Turkey" would be displayed on your screen in reverse video for  second, but it let you do it. (You were OK until you saved the document.) The best you can do sometimes is laugh when people do stupid things. There are usually very few correct actions and nearly infinite incorrect ones.

**Comment by xpusostomos** [comment]
I wonder if it wouldn't be nicer to have everything in the one file. Maybe all python, the first section would be what's now the sidecar variables, then some separator, then the action python.
Something like:
```
hotkey = Hotkey(modifiers=["<ctrl>"], key="c")
filter = Filter("... etc
#SCRIPT
keyboard.send_keys("blah")
```

Would make the code simpler too... don't even have to parse json, just execute it. From the user's point of view it would look the same.

**Comment by josephj11** [comment]
Interesting idea. I think it would cause more problems than it solves.

I edit my scripts in kate. Putting the metadata in with the script would open it up to accidental corruption. The code that reads and runs it would probably have to be significantly enhanced to defend itself from relatively random possibilities.

At the very least, we'd have to do something like adding a metadata hash to the file. If it didn't match the computed hash (checked every time) when loading the file, then something other than AutoKey changed it and that would cause it to be rejected.

Now, if a user screws things up by manually editing the metadata, it's their problem,  not ours. I like that!

Most users never need to look at the metadata directly; putting it in front of them might be confusing.

It would also cause the script file to be marked as changed when only metadata has been changed. That would be confusing when debugging a script failure by making it look like something was changed in a script that might be a couple of years old. This would be even worse if we modified a field in the metadata across all scripts. Then, the modification dates on all of them would change.

If we wanted to now, we could add binary data of any type to the metadata. That's probably not the best idea, but it wouldn't even be an option if we combined the script and the metadata in one file.

**Comment by xpusostomos** [comment]
I often thought resource fork file systems were a good idea, but they never took off...
* Binary data.. I presume with the sidecar you'd uuencode it or something and put it in the JSON. Under this idea you'd 
uuencode it into a string, same thing.
* Putting the meta data in front of the user.... it would only be that for the few that use external editors.
* Random corruption.. You mean like... using an external editor and corrupting the meta data? I mean, if you're going to edit stuff manually, you have to have some care anyway. You can edit the json and corrupt it too. But being Python, if you're using a python editor it would alert you to syntax errors.

But yeah, there would be some downsides definitely.

One half way proposition would be to store the config file as a separate Python file rather than a json file. I'm a big fan of using single languages for projects, and using a javascript notation in a python project, kinda seems weird to me, even though I know this format is incredibly popular. If it was Python you could even declare and share variables and stuff, though how the gui would cope with that is an open question. Maybe it would show the final evaluation and if you changed it, then you'd lose any hand-written stuff. And then  maybe an autokey collection of directories is an actual, regular python module like any other module, except that it follows a certain pattern that the gui can edit. But maybe some people don't even want the gui, they just want to code it up.

**Comment by BlueDrink9** [comment]
@xpusostomos how thoroughly did you test the conversion behaviour before opening this? An issue on the gitter with the new beta makes it look like the conversion isn't happening with any of the files.

**Comment by BlueDrink9** [comment]
Might be related to the version comparison, because we're on a 0.96.0 beta rather than the expected 0.95.11

**Comment by BlueDrink9** [comment]
Fixed now. The folder you had been looking through wasn't populated at that point. I updated it to instead look through all the loaded folders and their paths. The only side effect I can think of is that any dotfiles associated with those folders might not get loaded until the next run.

**Comment by BlueDrink9** [comment]
Actually this is an issue. (These are notes to self btw). The folder's json is loaded when the folder list is populated. If we wait for populating folders before upgrading the dotfiles, the old jsons for folders won't have been loaded.

A custom iterator over all folders would be elegant, but passing it might be another story.

The issue is just with phrases in the default folders I think, because those folders don't get added to autokey's data.

**Comment by xpusostomos** [comment]
I'm not quite sure what you are referring to, but it sounds like you have it under control. I did test it, but apparently you think I missed something.

**Comment by BlueDrink9** [comment]
Did you have anything in the default folder that you tested?

**Pull request merged**
