### PR TITLE
Bump Python versions in workflow files to satisfy issue #964.

### PR DESCRIPTION
**Pull request by Elliria**
* Bump Python version in the `build.yml` file to **3.11**.
* Bump Python version range in the `python-test.yml` file to **3.9** through **3.11**.

### CODE REVIEW

**Comment by BlueDrink9** [comment]
Was there a reason for 3.9 as the lower bound btw? I understand 3.11 is the latest that is currently passing tests. Are pythons < 3.9 still supported

**Comment by josephj11** [comment]
AFAIK, 3.7 is depreciated, but 3.8 should still be valid, but that's a guess. Is there a reason to jump past 3.8? Does it matter much if we do jump anyway? 

AFAIK, this version spec has no effect on end users unless they are cloning the repo on GitHub for private modifications. The population doing that at all is pretty small and those doing so on an old version of Python of likely to be vanishingly small.

**Comment by BlueDrink9** [comment]
I might be misunderstanding you Joe, but I think this test is valid for more people than cloners. Ultimately the versions affect what the tests run against, and therefore validates who can install and run autokey successfully. I think we should find out what the newest available version is on the oldest still-supported Ubuntu LTS, and use that as our yard stick?

**Comment by BlueDrink9** [comment]
Looks like [3.8 is the oldest version I would keep support for](https://packages.ubuntu.com/focal/python3)

**Pull request merged**
