### PR TITLE
Make packaging changes to satisfy #772 and #773.

### PR DESCRIPTION
**Pull request by Elliria**
I realize this will fail the tests because of dependencies, but wanted to do a pull request with hopefully-correct Python versions in it and also the necessary changes from apt to apt-get.

### CODE REVIEW

**Comment by Elliria** [comment]
According to someone on IRC, [this](https://github.com/autokey/autokey/blob/master/.github/workflows/python-test.yml#L158) is the problem.

**Comment by josephj11** [comment]
I'm not going to act on  this until the tests get fixed, but it looks great otherwise.

That file doesn't appear to have updated Python versions in it, so that seems like the first thing to fix.

Since it's in master and not in develop, IDK what to do. If we update it in master, does that create any problems for users that may download it now? Probably not, but how do we evaluate this? Can we expect that any current/new users will have sufficiently new versions of Python installed so this change won't break anything for them?

I suspect this is a non-issue, but I'd like to have something more concete than a guess to base that upon.

**Comment by Elliria** [comment]
No worries. We can close it. All the steps are in those two issues that it satisfies.

**Comment by Elliria** [comment]
> That file doesn't appear to have updated Python versions in it, so that seems like the first thing to fix.
> 
> Since it's in master and not in develop, IDK what to do. If we update it in master, does that create any problems for users that may download it now? Probably not, but how do we evaluate this? Can we expect that any current/new users will have sufficiently new versions of Python installed so this change won't break anything for them?
> 
> I suspect this is a non-issue, but I'd like to have something more concete than a guess to base that upon.

You're right and I should have fixed it above. The person in IRC who's helping was using the **master** branch at first until I noticed that and clarified that we want to be doing this in the **develop** branch. The same problem exists [here](https://github.com/autokey/autokey/blob/develop/.github/workflows/python-test.yml#L158).

And no, I don't think we want to tamper with the **master** branch with these version- and dependency-correcting changes because they're going to be messy and probably make things worse for a while as part of the process and we'd like **master** to remain stable. That way, if you want to add a Code of Conduct, for example, you'll be able to merge it in cleanly.

We'll need to find out from some seasoned project coders whether it's acceptable to update files in **master** or if they're somehow sacred once a release is out. I've been noticing little things in the code that are outright incorrect (like a reference to an old version of AutoKey, for example) that really ought to be corrected, but am unsure whether such corrections should happen in **develop** or **master** or both.

I also ran a lint test in a hard-core way on my local clone and all I can say is whee-doggy, there's enough stuff there to keep a girl busy for a very, very long time. It's lots of little and some not-so-little corrections that need to be made here, there, and everywhere.

**Comment by josephj11** [comment]
OK. Several things.

Nothing is sacred - except our good intent, but ...

When someone asks for help and tells me what version of AutoKey they are using, I want it to be "the one and only" version that we released with that release version. I do not want to have to look at the actual date, etc. to catch a moving target. I want code line numbers to stay constant... I don't want a traceback that takes me "somewhere near" the right line.

So, I am strongly against modifying any released code after the fact. Adding a disjoint file like a code of conduct that doesn't affect anything else still isn't the best idea, but the impact of doing so is very low. When balanced against the fact that our current release  cadence is glacial. It's worth doing.

So, I would make all changes in develop and put out point or, better yet,  subpoint (0.96.1.1, etc.) releases whenever needed. See [this](https://stackoverflow.com/a/65750/1239123).

Since AutoKey basically works, most, if not all, of the rest of what you are describing is probably best characterized as technical debt. Every project has this and older ones (like AutoKey) usually have a lot more than newer ones.

(Puts maintenance programmer hat back on) This is a slippery slope.

"If it ain't broke, don't fix it" is usually the best approach.

When you're not a master of the language and the application (and even if you are!), it's quite easy to "fix" something and, in the process, create side effects or other unintended consequences.

When you change something you have to test and QA it and everything else it touches. This isn't Haskell where you can prove your changes are correct. Also, anything you change has to be tested and QAed by everybody else too, so you are adding to other people's workloads as well.

So updating/adding comments anywhere is OK _if_ you're sure they're right, but changing code to make it pretter or more technically correct should only be done if you're changing that code anyway for some other reason.

Even comments can be dangerous. People are in a hurry. They will generally believe what they read and it will affect how they look at everything else.  If your comment says A does X, but it doesn't do that and only that exactly, it can blind the programmer from finding a problem. Or, even worse, it can lead them to add bad code that creates new problems because they were misled about something.

Comments also have to be updated when code changes. Sometimes, this gets missed.

You need to consider the cost/benefit. All resources are finite as we are accutely aware at the moment. If you are not dotting Is and crossing Ts, you could be adding a new feature, fixing a known bug, writing more of your great documentation, or becomming a more advanced Python/git/GitHub programmer, etc.

Maintenance programming is essentially a thankless task. When you get done, you often have nothing to show for it and no one even knows you did it let alone is grateful. It's an easy way to burn out on a project.

All of that being said, of course reducing technical debt is a good thing and needs to be done when possible, but it is best approached in small doses and when that code has to be modified anyway.

One thing you can usually do is add a comment that starts with "FIXME:", "WARNING:", or "NOTE:". Some editors, including kate, will recognize these tags and colorize or otherwise highlight them. Then, whoever comes later will notice your concerns.

**Comment by Elliria** [comment]
Then unless absolutely necessary (as in the case with that current pull release from the kind beneficiary who helped us out), all of my changes will be in the **develop** branch, so that that one stays ahead of **master** and doesn't inadvertently cause something to go wrong with it.

At this point, I know for a fact that I'm going to break **develop**, probably in glorious ways and repeatedly, before it's fixed. I'm doing that locally and keeping track of what I'm changing so that if I should happen to get it to actually pass all the tests locally, I'll be able to repeat it on GitHub. As a result, it will look like I'm not doing anything since all my changes will be happening here, but I want you to know that I'm doing what I can and am not going to walk away.

Thanks for the [point release](https://stackoverflow.com/a/65750/1239123) link. That will come in handy when it comes time for me to learn how the heck one puts out a new version.

**Comment by josephj11** [comment]
Go make some glorious omelettes!

 Since, for us, version 0 never changes,  our fourth level is like other's third levels, so I would use it that way with things like  0.96.1.1. We don't have anything like nightly builds, etc., so we're probably never going to have build numbers.

**Comment by josephj11** [comment]
@Elliria Obligatory [Dilbert](https://dilbert.com/strip/2023-02-22).

**Comment by BlueDrink9** [comment]
Just chiming in to say I'm very impressed with your work elleria, and with Joe's guidance. Great discussion in this thread.

In the past, small bugfixes were added into master as well as develop. In general, unless someone is using a version they've cloned themselves, no-one will be using the latest master unless it has a tagged release - which for bug-fixes, would be a minor version.

In other words, for small things you can feel free to PR into master. After it's merged, it's a good idea to PR master into develop, just to keep things a bit synced/ keep develop 100% ahead of master.

**Comment by josephj11** [comment]
@BlueDrink9 Thanks for your kind words.

I'm still not sure about changing a released master.

If someone has a distro with no AutoKey package, wouldn't they get it from the master branch using git?

If they want to attempt to modify code, wouldn't they also get it from main?

Or, if they get it from develop, won't they miss getting changes that were subsequently added to main?

I don't really understand how pip works at all. Does it have its own fixed copy of everything when we do a release?

Changing main between releases just seems like a support nightmare. When someone has a problem, we have no idea what their code base looks like if they didn't use a prepackaged version. It's bad enough that we can't look over their shoulder and see what's really happening as opposed to what they're telling us.

As a developer, that doesn't affect you at all unless you jump in on support. You can mix and match whatever you want as long as it all gets merged with no conflicts when you want to do a release.

It's my impression that with all your magic GitHub actions, etc., it should be quite trivial to put out a maintenance point release - once we get it to work at all again - so I don't see the advantage of altering master.

I do wonder how we would do a small fix release if we had already added a bunch of other unproven things to develop. I guess we would have to start over by forking the master and adding the small changes to the new fork and to develop. Once it was ready to be released, we could then merge that new fork back into main.

**Comment by BlueDrink9** [comment]
I understand your concern. In that case, we should add a bug-fix branch separate to develop. Develop contains too many new features, and while we could individually cherry-pick bugfix commits to master, I think it's easier to just store them in a separate branch then merge them into both develop and main.

**Comment by Elliria** [comment]
> Go make some glorious omelettes!

That would have been nice. As you saw, I was using the method of throwing spaghetti at the wall until it hopefully sticks.
 
> Since, for us, version 0 never changes, our fourth level is like other's third levels, so I would use it that way with things like 0.96.1.1. We don't have anything like nightly builds, etc., so we're probably never going to have build numbers.

I'd have to go grab that point-release link you provided and use it like a cheat sheet even to begin to know when or whether it was time for any of the variety of versions there seem to be. That sounds like one of those terrific things to make Somebody Else's Problem.

**Comment by Elliria** [comment]
> Just chiming in to say I'm very impressed with your work elleria, and with Joe's guidance. Great discussion in this thread.

You're very sweet and yes, @josephj11 has a way of noticing things that are easy to overlook and of relentlessly pursuing information about them. He's also a stabilizing force and seems to keep everyone grounded. And the addition of @userdocs into the mix at just the right moment has been absolutely amazing. I suspect that he/she is a wizard capable of immense magic.
 
> In the past, small bugfixes were added into master as well as develop. In general, unless someone is using a version they've cloned themselves, no-one will be using the latest master unless it has a tagged release - which for bug-fixes, would be a minor version.

Okay, that's good to know, although I know nothing about tagged releases.
 
> In other words, for small things you can feel free to PR into master.

How small? I'm assuming the fix of changing **apt** to **apt-get** would be considered small and can be done to both branches. But I'm curious what else would qualify as small.

> After it's merged, it's a good idea to PR master into develop, just to keep things a bit synced/ keep develop 100% ahead of master.

That sounds like it will be for @josephj11 to do since he wears the merge hat.

**Comment by Elliria** [comment]
Oh, hey @BlueDrink9, while we have your "ear", you're listed as one of AutoKey's packagers and we've been having a discussion in another thread about making changes to the [CHANGELOG.rst](https://github.com/autokey/autokey/blob/master/CHANGELOG.rst) file. It currently has a preview issue preventing it from being previewed when it's open in edit mode and it's also prevented from rendering in a "pretty" way (like the [README.rst](https://github.com/autokey/autokey/blob/master/README.rst) file does), which would perhaps make it more appealing to users. Both of those are the result of a couple of headings that use carets or plus signs instead of equal signs or dashes that seem to confuse GitHub.

Would changing:
```
foo
^^^
```
or:
```
foo
+++
```
to:
```
foo
---
```
have an impact on packagers and should it not be done? I tested it in a dummy repository in my profile and it made the file "pretty" and made it previewable, but I'm not sure what it would do to packagers.

Also, are there any other packaging-related pitfalls we should know about so that we know what to do or not do to keep everything going smoothly for everyone?

**Comment by Elliria** [comment]
> I don't really understand how pip works at all. Does it have its own fixed copy of everything when we do a release?

I'm pretty sure **pip** is just like **apt** and that they're both commands that lets us access collections of packages, with **pip** letting us have at the [Python Package Index](https://pypi.org/) and **apt** letting us have at the [Ubuntu epositories](https://packages.ubuntu.com/).

**Comment by Elliria** [comment]
> I understand your concern. In that case, we should add a bug-fix branch separate to develop. Develop contains too many new features, and while we could individually cherry-pick bugfix commits to master, I think it's easier to just store them in a separate branch then merge them into both develop and main.

That makes sense. I'm also still a bit confused about **master**, though. It's not intended for that to be "frozen" in any way? And the other branches are just so that if you're doing this type of work, you do it over here, and if you're doing that type of work, you do it over there, and when your work is finished, a copy of it always (**?**) goes to **master** and sometimes goes to other branches (like **develop**), too?

**Comment by BlueDrink9** [comment]
> Since, for us, version 0 never changes, our fourth level is like other's third levels, so I would use it that way with things like 0.96.1.1. We don't have anything like nightly builds, etc., so we're probably never going to have build numbers.


I missed this. Hard disagree on using a 4th number (we don't have one currently, right?). We should stick to semantic versioning, so the 3rd version should be incremented on bugfixes. A 4th number won't mean the right things

**Comment by BlueDrink9** [comment]
Re: changelog: nothing automatic parses it currently afaik, so change away. The github rst standard might have changed? All I packaged, really, is the pip stuff plus shoehorned a .deb build into the CI

**Comment by BlueDrink9** [comment]
Small changes for master = any bugfixes that touch a handful of lines and aren't likely to have side effects, plus anything that ostensibly works and doesn't affect the app itself - eg CI changes

**Comment by BlueDrink9** [comment]
Not sure I understand what you mean by doing work "over there" etc

**Comment by josephj11** [comment]
> I'm pretty sure **pip** is just like **apt** and that they're both commands that lets us access collections of packages, with **pip** letting us have at the [Python Package Index](https://pypi.org/) and **apt** letting us have at the [Ubuntu epositories](https://packages.ubuntu.com/).

Since that link uses the word "repository", I assume that when we do a release and the magic pip action occurs, that repository then contains an immutable copy of the whole project at that release level, just like a deb/RPM does. That's good.

**Comment by josephj11** [comment]
> > Since, for us, version 0 never changes, our fourth level is like other's third levels, so I would use it that way with things like 0.96.1.1. We don't have anything like nightly builds, etc., so we're probably never going to have build numbers.
> 
> I missed this. Hard disagree on using a 4th number (we don't have one currently, right?). We should stick to semantic versioning, so the 3rd version should be incremented on bugfixes. A 4th number won't mean the right things

OK. I stand corrected.

**Comment by josephj11** [comment]
> Small changes for master = any bugfixes that touch a handful of lines and aren't likely to have side effects, plus anything that ostensibly works and doesn't affect the app itself - eg CI changes

Anything like changing the CI or adding an unlinked file (like a code of ethics) directly to master would be fine with me. 

Small , safe changes aren't too bad, but they can still mess up line numbering if they add or delete lines. This isn't huge, but a ton of them, like technical debt corrections could really throw things off cumualatively.

Worst case would be that we would have to ask the issue poster to list a few lines before and after the exception line, so we'd know for sure where the probem occurred. Not a big deal, but an extra step in a process that may already have a lot of steps.

In Python, variables are allocated and typed upon use, so, theoretically, a one character change, e.g. to a variable name (from a typo, etc.), or undenting the last line of a block might get past all our tests and cause significant mayhem depending on the scope of that variable... If you were lucky, it would affect some edge case that wasn't tested for by the developer. So, what is a "small" change, really?

Again, this practice will cause pieces of main to be ahead of develop, which is OK, but it's one more thing to juggle when preparing for a new release.

**Comment by josephj11** [comment]
> That makes sense. I'm also still a bit confused about **master**, though. It's not intended for that to be "frozen" in any way? And the other branches are just so that if you're doing this type of work, you do it over here, and if you're doing that type of work, you do it over there, and when your work is finished, a copy of it always (**?**) goes to **master** and sometimes goes to other branches (like **develop**), too?

This is exactly what I'm talking about. You can do whatever you want, but some practices increase the overall complexity and lead to uncertainty - which adds overhead to procedures and to code review and, possibly to QA.

This increases the vulnerabilty surface of the project for very little benefit, except in edge cases of things that are isolated.

**Comment by josephj11** [comment]
> That sounds like it will be for @josephj11 to do since he wears the merge hat.

I'm happy to help witih version numbering and to push the "merge" button when apropriate, but if anything doesn't work first try, I really don't know how to fix it.

**Comment by Elliria** [comment]
> Re: changelog: nothing automatic parses it currently afaik, so change away. The github rst standard might have changed? All I packaged, really, is the pip stuff plus shoehorned a .deb build into the CI


Thank you. It's been like that as far back as I can remember and I've been using AutoKey for years. I'll probably still reach out to the other packagers first to make sure they don't have a purpose for it, but if they're fine with it, this will be a quick fix.

**Comment by Elliria** [comment]
> Not sure I understand what you mean by doing work "over there" etc

I'm updating it a bit after reading your conversation above about branches and point releases. 

**If I understand the branch structure and work-flow correctly:**
* The **master** branch is the base that should remain as stable as possible.
* The **master** branch reflects the basic code in the currently-available release, but may contain some minor changes that weren't put into the currently-available AutoKey release.
* The other branches (**beta**, **develop**, etc.) are there for doing different types of work.
* If you're adding a new feature, for instance, you do it the work in the **develop** branch.
* If you're doing a bug fix, for instance, you do it in the **bugfix/issue_XXX** branch (with XXX representing the issue number that's being worked on).
* When you're satisfied that your work is finished, you do a pull request.
* Once the pull request is merged into the project, if the newly-merged code in the **develop** or **bugfix/issue_XXX** (or any other non-master) branch is backwards-compatible and won't cause a major change to the stable code-base of the **master** branch, it can be merged into the **master** branch.
* Any **bugfix/issue_XXX** change that's accepted into the **master** branch should also be applied to the other branches.
* Some other changes that are accepted into the **master** branch should also sometimes be applied to other branches.

**What I'm unsure of:**
 * How does the **beta** branch work? Does that get kept up-to-date with the **master** branch until such a time as there's a new major change in one or more of the other branches (like the **develop** branch) that can be merged into it? And does that become the new release-candidate at some point?

**Comment by Elliria** [comment]
> Again, this practice will cause pieces of main to be ahead of develop, which is OK, but it's one more thing to juggle when preparing for a new release.

I'll try to help with that, @josephj11.

**Comment by Elliria** [comment]
> Since that link uses the word "repository", I assume that when we do a release and the magic pip action occurs, that repository then contains an immutable copy of the whole project at that release level, just like a deb/RPM does. That's good.

It looks like it. There are a few versions of AutoKey on [PyPi](https://pypi.org/project/autokey/#history).

Note that one of you who has access to PyPi on AutoKey's behalf will want to make sure they update the **Requires: Python >=3.5** line on that page to: ****Requires: Python >=3.7**

**Comment by josephj11** [comment]
> **If I understand the branch structure and work-flow correctly:**
> 
> * The **master** branch is the base that should remain as stable as possible.
> * The **master** branch reflects the basic code in the currently-available release, but may contain some minor changes that weren't put into the currently-available AutoKey release.
> * The other branches (**beta**, **develop**, etc.) are there for doing different types of work.
> * If you're adding a new feature, for instance, you do it the work in the **develop** branch.
> * If you're doing a bug fix, for instance, you do it in the **bugfix/issue_XXX** branch (with XXX representing the issue number that's being worked on).
> * When you're satisfied that your work is finished, you do a pull request.
> * Once the pull request is merged into the project, if the newly-merged code in the **develop** or **bugfix/issue_XXX** (or any other non-master) branch is backwards-compatible and won't cause a major change to the stable code-base of the **master** branch, it can be merged into the **master** branch.
> * Any **bugfix/issue_XXX** change that's accepted into the **master** branch should also be applied to the other branches.
> * Some other changes that are accepted into the **master** branch should also sometimes be applied to other branches.
> 
> **What I'm unsure of:**
> 
> * How does the **beta** branch work? Does that get kept up-to-date with the **master** branch until such a time as there's a new major change in one or more of the other branches (like the **develop** branch) that can be merged into it? And does that become the new release-candidate at some point?

I see a developer section of the wiki being written!

The Beta is only alive when there are sufficient changes to merit a new release. Usually, this would be a major release such as 0.97. When it has been suficiently tested, it will either replace or be merged into the master. At that point, it goes dormant until the next release is ready for beta testing. Since it will have all the CI/testing stuff in it, etc., we probably wouldn't delete it, but there's no point in updating it until we need it because a beta is pretty much feature and bug fix frozen (no new issues before release), but we want to be able to start/continue work on other issues in develop.

Usually, one or more release candidates would preceed the Beta. The Beta is saying we think this is good enough to release. Now you try it so we can be sure. But on a small project like this one, there might not be a distinction between RCs and Beta as was done with 0.96, where we had 10 beta versions that were release candidates, but not explicitly labelled as such.

A Beta can have some small open outstanding issues, but they should be as minor as possible. Generally, the only new stuff after the start the beta should be responses to problems discovered while testing it.

**Comment by Elliria** [comment]
Good to know. Thanks, @josephj11.

**Comment by josephj11** [comment]
Just updated my last post above. We can handle Beta creation/refreshing any way that we wat to. Theoretically, wiping it and starting over would be best because then you're sure there are no left-overs in it. It's like a fresh OS install instead of an upgrade. Upgrades keep all your nice customizations,but also keep all the things you tried once and forgot to delete, etc.

**Comment by Elliria** [comment]
Ah, okay. I just saw that and will add it to my notes. Thanks for your thoroughness.

**Comment by josephj11** [comment]
> > Again, this practice will cause pieces of main to be ahead of develop, which is OK, but it's one more thing to juggle when preparing for a new release.
> 
> I'll try to help with that, @josephj11.

Until we get a new lead developer (or you eventually step up), you _are_ the juggler.

**Comment by josephj11** [comment]
> Note that one of you who has access to PyPi on AutoKey's behalf will want to make sure they update the **Requires: Python >=3.5** line on that page to: ****Requires: Python >=3.7**

Apparently, I have a Pypi account. I had to look in my passoword manager. I have no idea what I'm doing with it though. I mainly have it for continuity, so we never get locked out.

**Comment by josephj11** [comment]
@Elliria As is quite evident, I know very little about Git/GitHub, but I have worked as a programmer on projects and teams, so I understand most of the basic concepts from experience. I have use some simple version control software before, but it was very primitive compared compared to Git/GitHub.

I also have had my own very small project on sourceforge for a very long time. It has no version control at all, but really needs it. I do it all manually. It needs an update that I have been putting off for a few years.

**Comment by Elliria** [comment]
No worries. We're both learning together. I've also used other version-control software, but don't have experience with git. We'll find our way through this forest.

**Comment by Elliria** [comment]
> Until we get a new lead developer (or you eventually step up), you _are_ the juggler.

Then I shall juggle.

**Pull request closed without merging**
