### PR TITLE
Upgrade develop branch to work with ubuntu-latest.

### PR DESCRIPTION
**Pull request by Elliria**
Added a fix for invalid values in setup.cfg.

### CODE REVIEW

**Comment by Elliria** [comment]
Guys, I'm making a spectacular mess of this.

**Comment by josephj11** [comment]
Even Linus didn't start out as a master of the universe - and he wrote git in his spare time while creating Linux.

Thanks for persisting with this. I'm sure we'll get it right eventually.

As you are doing, get the tests to pass when doing the absolute minimum changes to anything else (like apt).
The tests have to work before adding any normal complications.

**Comment by josephj11** [comment]
I attempted to read the test output.

It looks like it was happy until it got to ./tests/test_phrase.py.

That's some seriously strange code that looks like it's testing how phrases work with things like matching case. It complains about "legacy code" or something.

All I really got out of all of this is it looks like it almost worked.

Most things seem to pass with no errors.

**Comment by Elliria** [comment]
> Even Linus didn't start out as a master of the universe - and he wrote git in his spare time while creating Linux.

I'm taking great comfort in that and can only hope he's had some spectacular fails as well.

> Thanks for persisting with this. I'm sure we'll get it right eventually.

That's the plan. I'm keeping my hand on its throat.
 
> As you are doing, get the tests to pass when doing the absolute minimum changes to anything else (like apt). The tests have to work before adding any normal complications.

Will do. As soon as I saw that the very minor **apt** changes failed, I put those on hold. They can wait.

**Comment by Elliria** [comment]
No idea on the cause. I scrapped that commit and started over.

**Comment by BlueDrink9** [comment]
Xfail means expected failure. Known legacy test. Safe to ignore

**Comment by josephj11** [comment]
A search turned this up:

An xfail means that you expect a test to fail for some reason. A common example is a test for a feature not yet implemented, or a bug not yet fixed.

**Comment by Elliria** [comment]
Yeah, the XFAIL parts were fine, but the ERROR parts that and that blasted red X icon that were a wall.

**Pull request closed without merging**
