### PR TITLE
Update README.rst file to satisfy part of issue #681 and issue #779.

### PR DESCRIPTION
**Pull request by Elliria**
Update the README.rst file in beta to match the one in develop, and then note the change in the CHANGELOG.rst file.

### CODE REVIEW

**Comment by Elliria** [comment]
This is the update to the [README.rst](https://github.com/autokey/autokey/blob/beta/README.rst) file in the **beta** branch to make it match the [README.rst](https://github.com/autokey/autokey/blob/develop/README.rst) file in the **develop** branch.

This is also the update to the actions in the **beta** branch's [build.yml](https://github.com/autokey/autokey/blob/beta/.github/workflows/build.yml) file to match the updated versions in the **develop** branch's [build.yml](https://github.com/autokey/autokey/blob/develop/.github/workflows/build.yml) file.

This is also updates to the [CHANGELOG.rst](https://github.com/autokey/autokey/blob/beta/CHANGELOG.rst) file to note those changes.

**Comment by josephj11** [comment]
I will merge this whenever you request it.
I assume that it will continue our commits ahead/behind problems that still need to be resolved systemically.

**Comment by Elliria** [comment]
> I will merge this whenever you request it.

Let's not do it that way any more. A pull request is already a request, so it's redundant to do an additional request on top of that. I don't mind writing a description for each pull request s I've been doing, so I plan on continuing to do that.

> assume that it will continue our commits ahead/behind problems that still need to be resolved systemically.

Yes, and although it will add to the versioning mess, the diffs will either be identical or more similar this way (depending on whether there were differences other than that, which I didn't check). It will also make one less thing to have to do once the **beta** branch does get used.

Heads up that there are more changes coming for the **beta** and **master** branches as part of these updates, but I'll note them as I do them.

**Comment by josephj11** [comment]
OK. Feom now on, I will merge your PRs when they come in. I will review them as much as I can and let you know if I have any concerns before merging them.

**Pull request merged**
