### PR TITLE
[RFC] Remove PyKDE4 dependency, Qt UI rewrite. Ported to PyQt5.

### LINKED ISSUE #131: compileuic.sh   breaks build
after a pykdeuic4-3.5   run, autokey is totally broken. this app is low pre-alpha quality
not even the paths in  compileuic.sh    are correct. what is this ?

pristine master does build + run though. bad first impression.

### PR DESCRIPTION
**Pull request by luziferius**
Let’s resurrect the Qt GUI…
This time, I’d like to get some feedback and testing done _before_ this gets merged. @troxor \*wink\*
Issue tracker that can be used for this: https://github.com/luziferius/autokey/issues
# Dependencies
- Dropped: PyKDE4, PyQt4
- New: PyQt5
- New install/build-time dependency (Optional): `pyrcc5` CLI tool to compile Qt resource files. (Ubuntu package: `pyqt5-dev-tools`)

This is used to compile the UI files and AutoKey Icons into a python module. Also copying the icons guarantees that all AutoKey (`A`) icons are present under all circumstances, even if not present in the system icon theme. Missing icons happens when AutoKey is installed in a local Python virtualenv.
(All other icons are still loaded from the system icon theme.)
Unlike previously with python classes generated by pykdeuic4, the generated module must not be added to the repository. It is automatically generated during setup.py execution. This guarantees that all users always have the latest UI changes, without us having to regenerate automatically generated files.
If this tool is not present, the resource folder and icons are copied as-is as additional package data. The Qt GUI transparently handles both cases.
Thus installing autokey does not pull a hard build-time PyQt5 dependency in, for users only interested in the GTK GUI.
- New: `python3-pyqt5.qtsvg`. This is used for a workaround. See https://github.com/autokey/autokey/pull/154/commits/fbbb9303e44f55723774dc0bd41fbbed4ac1ea33 for details
- Dropped dependency: Python module `dbus.mainloop.pyqt5`.

Previously, autokey-qt used `dbus.mainloop.qt` to integrate the dbus interface with Qt. This caused me some threading related problems after the refactoring. Thus I stopped using the generic implementation in `autokey.common` and instead use the DBus interface implementation directly built into Qt5/PyQt5.
# Things done
- Cleaned up all UI files in the UIC directory, removed all KDE specific widgets and replaced with plain Qt ones.
  - Removed the `compileuic.sh` script and moved all UI files out of the uic directory. Fixes #131
  - Now, those live under `autokey.qtui.resources.ui`
- Replaced all pykdeuic4 generated code with those cleaned up UI files.
  - Classes using designed UI widgets load the files once during startup and directly inherit from the runtime-generated UI classes.
- Decomposed large source files.
  - All dialogs are grouped in a new `dialogs` package
  - All Settings/Preferences related widgets are grouped in a new `settings` package
- Many code style cleanups
  - e.g. replacing camelCaseVariableNames with the recommended_underscore_lowercase_style.
  - Removed all `import *` and `from x import *` imports
- Removed all PyKDE4 dependencies
  - Designed a new main application window replacing the KXMLGUI window.
  - Designed a new Settings dialog.
- Streamlined the `autokey-qt` script and moved to `autokey.qtui.__main__`
Defined a new entry point in setup.py named `autokey-qt`. This now works like the GTk-GUI.
- Reworked the window hide logic. Instead of destroying the window and re-creating it, it is merely hidden.
  - Now with 90% less object destructions/re-creations
  - Those nasty try-except blocks catching RuntimeErrors/AttributeErrors used as normal control flow are gone.
  - All internal state is kept, including #144, even text/item selections are kept across window closes/re-opens
- The enable monitoring/expansion/service checkboxes both in the settings menu and tray icon sync with the internal service activation state, meaning that the checkbox visibly toggles when the user presses the global hotkey.
- Improved the popup menu functionality: The menu elements now have proper icons depending on their types (Script, Phrase or Folder).
  - By extension, this works for the tray icon context menu, too!
- I tried fixing non-code files (like packaging files in the `debian` folder, but I don’t know if this went well)
  - (Hopefully completely) removed KDE related packages from various dependency lists.
- Compile the AutoKey UI files and other resources used by the GUI into a resource file when installing.
Tell setup.py to use the pyrcc4 CLI tool to build the file and deploy this compiled resources file instead of shipping the plain resources directory like it is done now.
- Ship the application icon in the resources directory, so that it is displayed even if it is not found in the system icon theme (like when installed using pip).
- Designed a VERY basic About AutoKey dialog. 
- Port from PyQt4 to PyQt5.
  - This should be way easier than ripping out PyKDE4.
  - Edit: It was quite easy: 
    - Adjusted imports for the new Qt package layout (mostly importing from QtWidgets instead of QtGui).
    - Replaced some deprecated function calls with the recommended ones
    - Fixed Icons, because PyQt5 did not like my static icon assignments…
- Use the DBus implementation built into Qt instead of `python-dbus`. autokey-qt does no longer depend on `dbus.mainloop.pyqt5` (the Qt5 equivalent to `dbus.mainloop.qt), which had caused problems in the past.
  - The new implementation does export a bit more than the `python-dbus` implementation still in use in the GTK GUI, but, as long as user code does not depend on the new, fancy introspection exports, both implementations are compatible.
# Future work
- https://github.com/luziferius/autokey/issues/6
- https://github.com/luziferius/autokey/issues/8
- https://github.com/luziferius/autokey/issues/9
- https://github.com/luziferius/autokey/issues/11
- https://github.com/luziferius/autokey/issues/17
- https://github.com/luziferius/autokey/issues/18

### CODE REVIEW

**Comment by troxor** [comment]
Wow, this is a ton of progress towards #56 . I don't personally run Qt on my system, but @xuzhao9 and others may be interested.

**Comment by sporkwitch** [comment]
I _do_ use Qt (KDE FTW), so this is great :)  Not looking forward to fixing the deps in the control file, though lol

**Comment by luziferius** [comment]
@sporkwitch You may want to look at the last few commits. I ripped out everything KDE related from all dependency lists I found.

**Comment by sporkwitch** [comment]
@luziferius yup, i got that, it's more just resolving which packages pull what from the ubuntu repos.  Probably will be easier than the initial bionic setup, since the changes are recent, not historic to dig through, so less trial-and-error heh

Thanks for the hard work, mate

**Comment by luziferius** [comment]
Ok. I did the last steps and ported the whole thing to PyQt5.
This should fix
- #56 
- Maybe #90, This looks like it is a weird Qt UI issue (probably caused by global menus).
- Maybe #77

Edit: I successfully built Debian/Ubuntu packages from the current branch HEAD, which look like working flawlessly (except for known, not UI related bugs, ofc ;) ).

**Comment by luziferius** [comment]
@troxor I think this can be merged. I ironed out all breaking bugs I found, autokey-qt now works smoothly on PyQt5.

**Pull request merged**
