### PR TITLE
Update GTK/Qt clipboard API documentation.

### PR DESCRIPTION
**Pull request by Elliria**
Update formatting and wording in the AutoKey [GTK](https://github.com/autokey/autokey/blob/master/lib/autokey/scripting/clipboard_gtk.py) and [Qt](https://github.com/autokey/autokey/blob/master/lib/autokey/scripting/clipboard_qt.py) clipboard API documentation.
*  Fix capitalization for consistency.
* Fix punctuation.
* Remove "mouse" and "X" from selection in descriptions.
* Update reference to clipboard for accuracy.
* Update references to selection for consistency.

### CODE REVIEW

**Review by josephj11 — APPROVED** [review]
Where does the selection actually live? Isn't it somewhere inside of X? Or is this looking forward to Wayland?

**Comment by josephj11** [comment]
Python 10 lint blew up on merge. Can't seem to find our repo URL. Weird. Rest of tests passed.

**Comment by Elliria** [comment]
Strange. I see nothing but passes from my end. I still suspect they're working on the pull-request interface, because we've had some odd errors lately that had nothing to do with us.

Anyway, apparently, [they're usually stored in the memory of the controlling application](https://askubuntu.com/questions/729360/where-are-the-contents-of-the-clipboard-stored), but I think that must be wrong. After all, you can copy or select something and close the program you got it from and it will still be available in Klipper.

In the [clipboard_qt](https://github.com/autokey/autokey/blob/master/lib/autokey/scripting/clipboard_qt.py) file I just edited, you'll see that I left the reference to **X selection** in [the main description for the **QtClipboard** class](https://github.com/autokey/autokey/blob/master/lib/autokey/scripting/clipboard_qt.py#L15).

I just checked the [clipboard_gtk.py](https://github.com/autokey/autokey/blob/master/lib/autokey/scripting/clipboard_gtk.py) file and realized that I missed a reference on [line 53](https://github.com/autokey/autokey/blob/master/lib/autokey/scripting/clipboard_gtk.py#L53), so I'll be fixing that momentarily. In that file, I intentionally left the reference to **X selection** in [the main description for the **GtkClipboard** class](https://github.com/autokey/autokey/blob/master/lib/autokey/scripting/clipboard_gtk.py#L26) and also in [the exception that's raised if the selection is empty](https://github.com/autokey/autokey/blob/master/lib/autokey/scripting/clipboard_gtk.py#L93)

**Comment by sebastiansam55** [comment]
@josephj11 I ran the workflow in autokey.github.io to regenerate the documentation, these changes should now be live. 


For future reference, you just need to go to "Actions" in that repo and select "Run Workflow"

**Pull request merged**
