### PR TITLE
Add distinction between left and right modifier keys

### PR DESCRIPTION
**Pull request by sebastiansam55**
WIP, like others have noted there are some major backend issues with making the distinction between the left and right shift.

### CODE REVIEW

**Comment by josephj11** [comment]
Could `<shift>` and the others be made to default to the left or right variant so that (most) old scripts would still work?
If someone has remapped one of the shift keys on their keyboard, this might cause them problems, but that should just be documented.

**Comment by BlueDrink9** [comment]
I looked into rebasing this onto develop, but the single commit is too huge. I'll ask you to do it yourself I'm afraid.

**Comment by rbreaves** [comment]
This is a very worthy inclusion, I have a large set of complicated remaps that only work with this sort of distinction setup.. I believe I can now make use of this project!

**Comment by sebastiansam55** [comment]
big changes related to this coming very soon, will be on a different commit!

**Comment by josephj11** [comment]
Cool!!

How will this be exposed in the Record Hotkey dialog? I assume that it should somehow default to the current behavior of left and right ones being identical. Maybe a checkbox could be added to disinguish between left and right variants when the keys are subsequently pressed.

**Comment by sebastiansam55** [comment]
see #844

**Pull request closed without merging**
