### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by kianmeng**

### CODE REVIEW

**Comment by josephj11** [comment]
Thanks!

Lots of typos to fix!

However, we try not to make changes to the master branch. They should be based on the development branch so they will be included in future releases (and subjected to our automated testing when more than just fixing text).

We are always happy to have new contributors. Please consider joining us over on [Gitter](https://gitter.im/autokey/autokey) where the developers and advanced users hang out.
There are also a few other issues labeled as Easy Fix and Good first issue, if you are interested in doing more and want to get into the flow of things.

**Comment by kianmeng** [comment]
@josephj11 Noted. Should I rebase to development branch ?

**Comment by josephj11** [comment]
I'm not one of the developers, but I believe it needs to be rebased. If you want to, you can wait until a developer comments here or you can ask @BlueDrink9 on Gitter.

**Comment by BlueDrink9** [comment]
Thanks for these! I did the rebasing for you out of apologies for the delay merging. You still get commit credit though!

**Comment by kianmeng** [comment]
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face:

**Pull request merged**
