### PR TITLE
WIP: Refactor UI and App code (Close #341)

### LINKED ISSUE #341: Make all code that updates/views/removes folders/phrases be run through engine.py
I've noticed there are bits and pieces of functional code unrelated to the GUI that is present (often duplicated) in the GUI apps.

I think we should refactor out all of this into its own file. I think that, ultimately, we want all the code that creates, retrieves or removes folders, phrases, hotkeys etc. to be in one class only, so that all apps and APIs etc go through that class.

It seems logical to use `engine.py` for this, so that the scripting api will always have the same power as the gui apps, if not more. Also, they already have the docstrings for the functions, so it would be easier for collaborators to understand the core code.

The downside is that I don't know if code for running scripts fits together with modifying items.

I'd also like to combine functions like run_script and run_subscript, because they feel like duplicated code.

I also want to refactor the UIs such that any code related to the `app` setup is separate, since that could be shared also.

Doing this will help keep the two UIs more separated, and make it easier to create new UIs if we wanted to.

### PR DESCRIPTION
**Pull request by BlueDrink9**
Hi Thomas, I'm starting on a refactor of the UI and app code, to separate logic out of the GUIs. It's quite a big task, and I'm not confident of how well I'll be able to test it, so I'd
appreciate close reviews if you have the time.

### CODE REVIEW

**Comment by BlueDrink9** [comment]
For starters, I've taken code out of `gtkapp.py` and moved it to new file `BaseApp.py`. Tests just check whether Exceptions are raised, mainly to ensure I haven't missed any names.

**Comment by koutsie** [comment]
any updates to this?

**Comment by josephj11** [comment]
@koutsie BlueDrink9 recently said he was planning to become active again after some time off and he's been commenting here again, but we haven't seen any new PR's from him yet. If this issue interests you, I would assume you have some Python skills. If you'd like to contribute, there's plenty of room for improvements. You can just jump in . Feel free to join the other developers/contributors on [Gitter](https://gitter.im/autokey/autokey) to discuss your ideas and what might be the best ways for you to participate.

Note, however, that we do not currently have lead developer(s) to manage the development/deployment process, so until someone steps up, we can't release anything. I am merging some very simple PRs into the development branch, but I'm not a Python developer, so I'm not touching anything that makes significant changes/enhancements.

**Comment by koutsie** [comment]
Ahaa, i'll need to see when i have a *bit* more free time.

**Comment by BlueDrink9** [comment]
Yeah, just been a case of getting around to it on my end. Should start contributing soon. This PR is pretty outdated, and I'll probably start it again attacking from a different direction.

@koutsie feel free to ask questions, here or on the Gitter. Tag me and I'll try my best to help, although I'm not familiar with a lot of the codebase.

**Comment by BlueDrink9** [comment]
Note to self: while the code changes were unhelpful, the tests may still be useful for boosting coverage. @BlueDrink9

**Pull request closed without merging**
