### PR TITLE
Add .github/ISSUE_TEMPLATE/bug.yaml to repository

### PR DESCRIPTION
**Pull request by Elliria**
Hey there,

I've created the ```.github/ISSUE_TEMPLATE/bug.yaml ``` file with quite a bit of help from Joe and we feel that it's ready for "prime time" in the AutoKey repository. Hopefully, you do, too. I'm also open to suggestions for ways to improve it.

I'm not sure if this pull request will include all 100 commits that I put into this as part of messing around with it. Many of those commits are in varying states of brokenness as I learned YAML, and as part of messing around, I had originally deleted the ```.github/ISSUE_TEMPLATE.md``` file, but later realized that that wasn't necessary, so I put it back. If you're stuck with all 100 commits and if there's a way I can do a cleaner (and smaller) pull request with just the one file, I'd be happy to give that a try.

All you need for the AutoKey repository is the current copy of the ```.github/ISSUE_TEMPLATE/bug.yaml ``` file. Hopefully you can get that from this pull request. Oh, and I hope you like the template.

### CODE REVIEW

**Comment by josephj11** [comment]
I don't know how, but there's a way to squash all these into one commit instead of so many. I've seen it done before.

**Comment by Elliria** [comment]
I hope so. I'll see if I can find it. Otherwise, I could get rid of my fork, fork it again, and just add that file as is without any other commits and then do a pull request from that new one. There should be a way to do it without that, though.

**Comment by BlueDrink9** [comment]
Don't worry, I can squash as part of the merge

**Comment by BlueDrink9** [comment]
Congrats and thank you!

**Comment by Elliria** [comment]
Thank goodness that you were able to do the squashing. I'll try to prevent this sort of thing by doing experimentation in a dummy repository if there's any more of this type of learning from the ground up in the future.

**Comment by Elliria** [comment]
Can that fork at my end be totally obliterated now without having any effect on the pull request? It's not prompting me to do that like it did the last time.

**Comment by BlueDrink9** [comment]
It can. It will destroy the commit history, since it was squashed and merged as a single commit - but you don't care about that right?

Regarding dummy repo - nah, git is very flexible like that.  You can always fix things up. Plus it can be helpful to see the process.

**Comment by Elliria** [comment]
Okay, good to know. Thanks for the help. In this particular case, it would probably be painful to go through all the commits because I was bumbling around for a while before I got the whole thing working. At one point, I had just saved a change when GitHub went down and I thought I had caused it. I was waiting for sirens and an ominous knock at the door.

**Pull request merged**
