### PR TITLE
Upgrade develop branch to work with ubuntu-latest.

### PR DESCRIPTION
**Pull request by Elliria**

### CODE REVIEW

**Comment by Elliria** [comment]
I think I've had enough of it for today. A girl can only get smacked down by GitHub so many times in one day. It's definitely an improvement, though. I'm enjoying those four green check-marks.

**Comment by BlueDrink9** [comment]
💕 spectacular work! 

I'm a little confused by the failing test error. Looks like `latest` doesn't have `xhost` available… I imagine the fix will be find and install the package that provides it?

**Comment by Elliria** [comment]
Thanks, but it's still failing, so for me it's still a wall. I think I might know what's wrong and will come back to it after dinner:

Take a look at [GitHub's Ubuntu 22.04 runner image](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md). It looks like they just updated the allowable Python versions and none of our code (master included) is currently configured for Python 3.10.6, which is what GitHub has installed and is using for these tests.

Also, one of the many PRs that I did today showed failures on tests below Python 3.7.15, so I changed my minimum levels in **setup.py** to that (the **master** branch still needs the sane change). I don't, however, know what resource we would use from now on to find that information out. I'd rather not be finding it out in failed tests. I'd say we could use [GitHubs Python Version Manifest](https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json), but if you do a search for **22.04) on that page and scroll way down, you'll see that it says that the earliest supported Python 3 version is Python 3.7.13, so that page isn't kept up-to-date.

**Comment by Elliria** [comment]
It's also possible I caused the xhost error. I did one thing that I was unsure of. In [line 140 of setup.py](https://github.com/Elliria/fork/blob/develop/setup.py#L140), I changed the value to 3.7.15 (x.x.x format) when the original value used x.x format. I have no idea whether that would confuse GitHub, but I figured that since they wanted a greater than or equal to, it should be specific. I could try reversing that and making it 3.7 to see if that makes the tests happy.

**Comment by userdocs** [comment]
If you fork the main repo but only choose the fork the main branch, you'll get that coverage error. I assume the cause is related to both this PR and my example.

https://github.com/userdocs/autokey/pull/1

@Elliria so I don't think it's anything you did specifically.

I'm not really familiar python so I did not investigate why tox is doing this. If someone knows that would be great. Someone who understands tox/covergage/py and knows why it behaves this way.

OR it might be safe to ignore the errors and not have the worklow fail and just continue.

This is what needs to be established. If it's a safe to ignore/continue error, which can be done.

**Comment by BlueDrink9** [comment]
Failing tests will block automatic releases, which will be a nuisance. So it will be good to get it fixed

**Comment by BlueDrink9** [comment]
Probably not your fault elleria, looks like tox is behaving as expected. I'd say it's a legitimate failure. We need to add xhost as an explicit apt-get dependency, probably. It must have been an implicit one before

**Comment by josephj11** [comment]
@userdocs Thanks for all your time and effort helping us! We really appreciate it.

**Comment by userdocs** [comment]
I might have confused myself on the fork error, It appears related to a requirement to fork the entire repo to get the tags.

If you just fork main there are no tags and the check fails.

```py
=================================== FAILURES ===================================
_________________________ test_version_number_accurate _________________________

    @pytest.mark.skipif("CI_test" in get_recent_git_tag(),
        reason="Don't test version for CI_test tags")
    def test_version_number_accurate():
        # git_tag_version = get_recent_git_tag(["--match='v*.*.*'"])
        git_tag_version = get_recent_git_tag()
>       assert_that(git_tag_version, is_(equal_to("v"+autokey.common.VERSION)),
        "Ensure the most recent git tag version matches the version number in lib/autokey/common.py")
E       AssertionError: Ensure the most recent git tag version matches the version number in lib/autokey/common.py
E       Expected: 'v0.96.0'
E            but: was ''

tests/test_common.py:38: AssertionError
```

**Comment by userdocs** [comment]
It is resolved by `apt-get install x11-xserver-utils` 

I added a PR to the fork that will fix it

https://github.com/Elliria/fork/pull/1

Here you see it works.

https://github.com/userdocs/autokey/actions/runs/4266979632

**Comment by Elliria** [comment]
> If you fork the main repo but only choose the fork the main branch, you'll get that coverage error. I assume the cause is related to both this PR and my example.

Then it couldn't have happened in my PRs, because each time, I did the edits in the **develop** branch and did the PRs from there. I did fork just **master** at one point today, but with all this coding, I'm getting a bit tangled up. I realized it immediately, scrapped the fork, and grabbed a fresh, proper one before making the changes and doing a PR.
 
> @Elliria so I don't think it's anything you did specifically.

Well, I copied your known-good commits into my fork and that apparently wasn't enough for the **develop** branch to get those awesome green check-marks that you got. I also did that again and added some additional version changes and a repair I'm not fully sure of in the [setup.cfg ](https://github.com/Elliria/fork/blob/develop/setup.cfg#L45) file after one of the GitHub errors complained about leading white space and suggested the use of commas instead. Fixing that still left it broken, which is interesting. 
 
> I'm not really familiar python so I did not investigate why tox is doing this. If someone knows that would be great. Someone who understands tox/covergage/py and knows why it behaves this way.

My goodness, you really are a wizard. For someone who isn't really familiar with Python, you sure worked some very quick magic and made it look effortless.
 
> OR it might be safe to ignore the errors and not have the worklow fail and just continue.
> 
> This is what needs to be established. If it's a safe to ignore/continue error, which can be done.

We definitely want to pass the tests, and at this point, it's my mission in life to get all the green check-marks.

**Comment by Elliria** [comment]
> Failing tests will block automatic releases, which will be a nuisance. So it will be good to get it fixed

Speaking of automatic releases, will we know when one of those happens so we can spread the word? And what triggers one of them?

**Comment by Elliria** [comment]
> I might have confused myself on the fork error, It appears related to a requirement to fork the entire repo to get the tags.
> 
> If you just fork main there are no tags and the check fails.

That might explain why my local **tox** tests fail when run on an as-yet-unedited clone of my fork's **develop** branch, but pass when run on a clone of its **master** branch.

I clone **develop** with this command and it fails all **tox** tests:
```
git clone --branch develop --single-branch https://github.com/Elliria/fork.git
```
I clone **master** with this command and it passes all **tox** tests:
```
git clone https://github.com/Elliria/fork.git
```

I assume I'll have to clone without specifying a branch to avoid that, but I don't know how I'm going to reach inside of it to get at the **develop** branch once it's sitting there all pretty in my VM. I suspect there will be some plucking going on and I suppose I really should go and take some of those courses that GitHub offers for free.

**Comment by Elliria** [comment]
> It is resolved by `apt-get install x11-xserver-utils`
> 
> I added a PR to the fork that will fix it
> 
> [Elliria#1](https://github.com/Elliria/fork/pull/1)

Got it. Thank you. It's perfect.
 
> Here you see it works.
> 
> https://github.com/userdocs/autokey/actions/runs/4266979632

It looks beautiful. More of those glorious green check-marks. Now I should try doing a PR with that to the AutoKey repository to see if I, too, can get some green check-marks before bed.

**Comment by BlueDrink9** [comment]
> > Failing tests will block automatic releases, which will be a nuisance. So it will be good to get it fixed
> 
> Speaking of automatic releases, will we know when one of those happens so we can spread the word? And what triggers one of them?
> 

A git tag on master triggers them. Iirc I wrote about it in CONTRIBUTERS

Thinking aloud: I wonder if I should have made that git tag test more robust. It only needs to run for release tests, because it is only there to ensure the autokey version is correct. Maybe if we include a fetch step in the CI actions, and create some way to check whether it's a release (or perhaps even just master) test…

**Comment by josephj11** [comment]
I may be missing something here. First, AFAIK, it can only run on the master branch because there's only one set of everything per release.

Second, since the tag can only be set by an authorized user, isn't it more of an "actuator" switch than a data value? Does it matter what the new value is? How is it used?

**Comment by BlueDrink9** [comment]
New tag value sets the version in pypi etc. However the value autokey shows in its menu and cli is written in code. The test checks that the latest tag matches the version in code

**Comment by Elliria** [comment]
> > Speaking of automatic releases, will we know when one of those happens so we can spread the word? And what triggers one of them?
> 
> A git tag on master triggers them. Iirc I wrote about it in CONTRIBUTERS

Yep, you did. I missed it. And of course we'd know because we'd be doing the tagging.

By the way, I noticed that that file contains information in the **beta** branch that's missing from **develop** and **master**. Is it okay for me to copy over information from **beta** that applies to either or both of those?

> Thinking aloud: I wonder if I should have made that git tag test more robust. It only needs to run for release tests, because it is only there to ensure the autokey version is correct. Maybe if we include a fetch step in the CI actions, and create some way to check whether it's a release (or perhaps even just master) test…

Yes, please, whatever you think is best.

**Comment by Elliria** [comment]
> I may be missing something here. First, AFAIK, it can only run on the master branch because there's only one set of everything per release.
> 
> Second, since the tag can only be set by an authorized user, isn't it more of an "actuator" switch than a data value? Does it matter what the new value is? How is it used?

It seems that anybody can create a tag and it will be up to you whether you accept it in their PR: [https://stackoverflow.com/questions/18216991/create-a-tag-in-a-github-repository](https://stackoverflow.com/questions/18216991/create-a-tag-in-a-github-repository)

Also, tags and branches are unrelated, because tags point to a commit rather than a branch, so tags can be done from any branch: [https://stackoverflow.com/questions/14613540/do-git-tags-only-apply-to-the-current-branch](https://stackoverflow.com/questions/14613540/do-git-tags-only-apply-to-the-current-branch)

You can get to our tags from the little "47 tags" link beneath the menu on the main AutoKey page. These are our tags: [https://github.com/autokey/autokey/tags](https://github.com/autokey/autokey/tags)

Last, but not least, you must tag to put out a release, because releases are based on tags.

**Comment by Elliria** [comment]
> The test checks that the latest tag matches the version in code

Ah. No wonder it's failing, then. Check out [line 185 in **master**](https://github.com/autokey/autokey/blob/master/setup.py#L185)

We'll also need to update [line 191 in **master**](https://github.com/autokey/autokey/blob/master/setup.py#L191) since our current minimum Python version is 3.7.

I'll do those and see if that fixes it. Update: Yep, it looks like it worked. All checks pass and I don't see any red x marks in PR #790.

**Comment by BlueDrink9** [comment]
Nope, those keywords have nothing to do with the build. They're purely for pip searching. Only 191 should change.

Yes, update from beta sounds good

Tags aren't associated with branches, but not every branch has every tag; so it only works if the master branch contains the tagged commit. Using merge commits for PRs instead of rebasing ensures tags on PR commits don't trigger releases when merged

Iirc it also only works if the tag is formatted like a version

**Comment by Elliria** [comment]
So, don't change [line 185 in **master**](https://github.com/autokey/autokey/blob/master/setup.py#L185)? I've currently got a PR that does change it. Should I cancel it?

**Comment by Elliria** [comment]
> Using merge commits for PRs instead of rebasing ensures tags on PR commits don't trigger releases

That sounds very, very important. I hope you understand it, @josephj11, because I'm not at the point of understanding rebasing yet.

Thanks to @userdocs, I did have the opportunity to merge a PR into my fork, so I saw how that's done.

**Comment by josephj11** [comment]
Nope. All this tagging is new to me. I understuans what rebasing is, but that's it. IP kiave never worked wiptih git before this unless so[meone told me exactly what to do.

Here's my guess: when PRs come in, there's a button to merge them. That should not trigger a release.

Rebasing means you wrote your code against one branch (like develop), but want to apply it to another branch (like main). Since chages are stored in something like diff format, applying them directly would potentially change the wronglines in the new target. Rebasing aligns the changes (diffs) made on one branch with the code on the t=other target branch. Beyond that, I don't know why doing ipt ne way or the other has anything to do with triggering a GitHub action to generate a release. I haven't looked into GitHub actions at all.

**Comment by Elliria** [comment]
Thanks for the information on rebasing. I'll add that to my notes.

**Comment by josephj11** [comment]
Like we say in crypto, DYOR. Anything I tell you about git/GitHub is based on heresay/very little experience. Or maybe, trust, but verify. ;)

**Comment by Elliria** [comment]
Same here. We're learning together.

**Pull request closed without merging**
