### PR TITLE
Github action for old autokey documentation

### PR DESCRIPTION
**Pull request by sebastiansam55**
Uploads and pushes to github pages environment. 

Manual trigger only.

### CODE REVIEW

**Comment by josephj11** [comment]
@sebastiansam55 I added you to the contributors team, so you should have access now. Make sure it works for the github.io stuff as well. I left both branches set to use GitHub Actions, but with jekyll unconfigured.
Thanks.

**Comment by sebastiansam55** [comment]
@josephj11 
I tagged you in that other thread on autokey.github.io, but that repo isn't tied to the Contributors group so I don't have access to it, I'll merge this and get it up and running now.

**Comment by sebastiansam55** [comment]
And boom the old documentation is live at https://autokey.github.io/autokey/

**Comment by josephj11** [comment]
It's amazing how much faster things get done when you actually know what you're  doing!

**Comment by josephj11** [comment]
I think I fixed it by adding that repository to the team. Try it now.

**Comment by sebastiansam55** [comment]
yep, merged, it's live now https://autokey.github.io/

**Comment by sebastiansam55** [comment]
And looks like the Edit on Github functionality works correctly.

**Comment by josephj11** [comment]
Great work. Not sure what your last comment refers to. I'll review everything later, but I'm pretty sure it's fine.

**Pull request merged**
