### PR TITLE
Remove errant line from master CHANGELOG.rst file

### PR DESCRIPTION
**Pull request by Elliria**
Remove errant duplicate line on [line 89](https://github.com/autokey/autokey/blob/master/CHANGELOG.rst#L89) in the `CHANGELOG.rst` file on the **master** branch that references issue #383. See the duplicate on [line 262](https://github.com/autokey/autokey/blob/master/CHANGELOG.rst#L262) in the same file.

### CODE REVIEW

**Comment by Elliria** [comment]
Note that the duplicate line is not an issue in the `CHANGELOG.rst` file on the [beta](https://github.com/autokey/autokey/blob/beta/CHANGELOG.rst) branch or the [develop](https://github.com/autokey/autokey/blob/develop/CHANGELOG.rst) branch.

**Comment by Elliria** [comment]
Also note that I didn't create a changelog entry for this fix since it's a cleanup of the [CHANGELOG.rst](https://github.com/autokey/autokey/blob/master/CHANGELOG.rst) file.

**Comment by josephj11** [comment]
This appears to be technically correct, but is it worth a PR by itself?

**Comment by Elliria** [comment]
Yes. I'd like to keep the steps separate since the next step will be big and I didn't want that to get lost in it. Thank you for merging it.

**Pull request merged**
