### PR TITLE
 Update to latest action versions in build.yaml in develop branch.

### PR DESCRIPTION
**Pull request by Elliria**

### CODE REVIEW

**Comment by Elliria** [comment]
This is an update to the **GitHub Actions** in the [build.yml file](https://github.com/autokey/autokey/blob/develop/.github/workflows/build.yml) file. Would you like this same update to be done to the [build.yml file](https://github.com/autokey/autokey/blob/beta/.github/workflows/build.yml) in the **beta** branch and the [build.yml file](https://github.com/autokey/autokey/blob/master/.github/workflows/build.yml) in the **master** branch? The [python-test.yml](https://github.com/autokey/autokey/blob/master/.github/workflows/python-test.yml) file received these updates in all three branches.

**Comment by josephj11** [comment]
IDK what this PR does or what the different action versions are. I'm happy to merge it once I have some idea of what it is.

**Comment by Elliria** [comment]
The actions are scripts that we've gotten from the GitHub [Marketplace](https://github.com/marketplace) (you can get to it from the **Marketplace** link in the GitHub toolbar. Those are GitHub-provided and user-provided scripts that can automate a large variety of tasks.

They're used in our [workflows](https://github.com/autokey/autokey/tree/master/.github/workflows) to automate tasks when specific conditions are met (think of it kind of like GitHub's version of AutoKey).

For example:

We have actions that create our documentation pages. If you click on the [pages.yml](https://github.com/autokey/autokey/blob/master/.github/workflows/pages.yml) file inside the `/.github/workflows/` directory and then click the pencil as though you're going to edit the file, you'll see the actions that are being used by that script inside the panel on the right of the page. You can also do a search for **actions/** in the file to see where and how they're being used. You can cancel out of there when you're done and nothing will change.

We also have actions that run tests (like the ones that you see whenever pull requests are made). Those are in the [python-test.yml](https://github.com/autokey/autokey/blob/master/.github/workflows/python-test.yml) file. You can examine that file in the same way.

Last, but not least, we have actions that run when AutoKey is built. That's the [build.yml](https://github.com/autokey/autokey/blob/master/.github/workflows/build.yml) file. That one can also be examined in the same way.

If you look through those and find an action line that you're interested in, like the **actions/cache@v2** line, you'd do a search for its name (in this case, it's the **cache** action) inn the [Actions section in the Marketplace](https://github.com/marketplace?category=&query=&type=actions&verification=) to see if the **cache** action is still at version 2 as it is in our file. You can click on its name in the list of actions that show up when you do the search and then look what the latest version is. As you can see, if you've been following along with this, the [Cache](https://github.com/marketplace/actions/cache) action is at version 3, so we need to update.

That's what I'm doing. I've listed off the individual actions that I've changed and you can also see them if you look at the commit diffs in the pull requests. In this particular pull request, [this diff](https://github.com/autokey/autokey/pull/826/commits/83edd82238c3629bb23bff4a6bf050a71d752bb7) shows what I changed. You can always go to the Marketplace and check them if you'd like to double-check my work. After all, nobody's perfect and there's always the chance that something got overlooked or there was a typo or something. Or you can live dangerously and press that **Merge** button and if everything blows up, you can always blame me. Either way, we'd figure out how to undo anything we've done.

**Comment by Elliria** [comment]
By the way, my new favorite teacher, Victor, has a [YouTube video on GitHub Actions](https://www.youtube.com/watch?v=eZcAvTb0rbA) that taught me a heck of a lot. It's glorious to be a fly on the wall and look over his shoulder at what he's doing as he explains *why* and *how* he does it. I think I'm his new number-one fan.

**Comment by josephj11** [comment]
IIUC, we use these GitHub actions "as is" and they don't autoupdate when a new version comes out, so you're doing it manually. In that case, this is simple maintenance.

We always have revert, so I'll merge (living dangerously).

The above is great stuff to add to the wiki - or wherever you're keeping developer aids.

I never cease to be amazed by how much effort people put into helping others. It's almost totally opposite of how things work in the closed source world.

**Comment by Elliria** [comment]
We do manually update those and other versions as well. It's not bad, though. Once you find them all, it doesn't take much time to do it. Would you like this done to **beta** and **master** as well? The [python-test.yml](https://github.com/autokey/autokey/blob/master/.github/workflows/python-test.yml) file received these updates in all three branches, so it stands to reason that this file should, too.

I've got a collection of information in my personal wiki that will all go into an AutoKey wiki page for developers and be linked to from [CONTRIBUTORS.rst](https://github.com/autokey/autokey/blob/develop/CONTRIBUTORS.rst).

And, yes, I'm also heartened by seeing how much help people give to others. Did you look at how many actions and apps there are on the GitHub [Marketplace](https://github.com/marketplace)? There are **17893 actions** and **719 apps**, many (possibly even most) of which were user-contributed.

**Comment by josephj11** [comment]
I can't advise you on things I don't understand. If you feel they need to be updated, do it. It sounds like you'd have to do it eventually anyway unless we change our release methodology.

**Pull request merged**
