### PR TITLE
remove unused import

### PR DESCRIPTION
**Pull request by 0xwho7**

### CODE REVIEW

**Comment by 0xwho7** [comment]
#663

**Comment by josephj11** [comment]
Thanks!

We try (for the most part) to leave the master branch unchanged between releases. PRs should be made relative to the development repository. In this case, (if this is correct) it's probably safe enough to go directly into the beta repository. (I'm not one of the devs.)

I'm not sure where this is in the code, but it appears to be within AutoKey itself. I haven't looked at this part of the code. What I was addressing in the issue were two of the example script files that come with AutoKey that include import time statements. I don't know if AutoKey itself needs to import time.

If you're interested in becoming more active in the project, consider joining us over on [Gitter](https://gitter.im/autokey/autokey) where the devs and advanced users hang out and discuss things.

**Comment by 0xwho7** [comment]
Thanks for clarifying, i wasn't exactly sure which files you were referring to, so i just went through the imports and removed the one which wasn't being used. I'll definitely join the Gitter!

**Comment by BlueDrink9** [comment]
Joseph is right about changes to master. Especially in the tests, because they have been totally re-written so this PR would just cause merge conflicts. Thank you for contributing!

**Pull request closed without merging**
